src/visibility-and-privacy.md
Re-sent https://github.com/rust-lang/rust/pull/40134#issuecomment-284171042 here.
=> Reworded the rule about accessing public items.

src/attributes.md
see https://github.com/rust-lang/rust/pull/40332
=> Fix links to the book

stable-check/src/main.rs
so that this passes tidy on rust master
=> Add license to stable check

src/items.md
It's a really silly statement.
r? @QuietMisdreavus
=> Remove segmented stacks statement

src/SUMMARY.md, src/glossory.md
Hi, i'm trying to build a glossary or vocabulary for all the nouns associated with Rust. Now i've started off picking out some descriptions from The Book,  libstd docs, and Wikipedia. This is only a starting point, and far from a satisfying, but I'd love to hear what people think of it. Feel free to add, edit, and remove anything in this PR!
=> [WIP] Add a glossory.

src/crates-and-source-files.md
=> Added crates grammar

src/macros.md
=> Fix broken links in macros chapter (issue #82)

src/tokens.md
=> Add boolean literal's grammar

theme/index.hbs
Fixes #118.
Because we modify index.hbs, we should occasionally compare with
mdbook's own copy and rebase our changes onto it.
=> Add best-effort warning header

src/items/modules.md
=> Modules grammar

src/expressions/literal-expr.md
=> Literal expression grammar

src/expressions/return-expr.md
=> Return expression grammar

src/items/extern-crates.md
=> Extern crate grammar

src/items/use-declarations.md
=> Use declaration grammar

src/introduction.md
=> Specify stability scope in introduction.

src/items/unions.md
=> Union item grammar

src/items/static-items.md
=> Static item grammar

src/items/type-aliases.md
=> Type alias grammar

src/glossary.md, src/items/traits.md, src/types.md
Too tired to work on anything big tonight; so have a few small misc. changes.
=> Small changes around trait objects

src/statements.md
I should have let Travis wait...this fixes the example to compile.
=> Fix broken example in previous PR

src/expressions/call-expr.md, src/types.md
Also more links in call-expr.md.
Fixes #72.
=> Say what traits that function items impl by default.

theme/index.hbs
=> add a link to the print button to make it work again

src/items/functions.md
As suggested in https://github.com/rust-lang/rust/pull/46833
=> Document "prevent unwinding into FFI"

src/type-layout.md
See https://github.com/rust-lang/rust/pull/46156.
=> Add size of bool

src/type-coercions.md
This finishes documenting RFC 0241.
=> Document that &mut T can deref-coerce to &U.

src/expressions/method-call-expr.md, src/items/associated-items.md, src/items/functions.md, src/items/traits.md
Also re-add a description of provided implementations.
=> More cleanups related to methods.

src/keywords.md
Fixes #319
As per https://github.com/rust-lang/rust/pull/49699
=> Removed 'proc' keyword

src/macros-by-example.md
=> document :lifetime

src/items/implementations.md
=> consider -> considered

src/types.md
r? @matthewjasper 
While we wait for the comprehensive docs, it'd be nice to have a placeholder so that we at least acknowledge it exists.
=> Placeholder docs for impl Trait

src/attributes.md, src/trait-bounds.md
=> Fix links for update in rust-lang/rust

src/expressions/block-expr.md, src/items/implementations.md, src/statements.md
Fixes https://github.com/rust-lang-nursery/reference/issues/374
Cc @Havvy
=> fix some link fragments

src/attributes.md
I don't know much about the organization of this book, but this seems an ok place to put it.
cc https://github.com/rust-lang/rust/pull/51974
=> Mention the global_allocator trait

src/behavior-considered-undefined.md, src/unsafety.md
=> Warning about UB being not being complete

src/keywords.md, src/undocumented.md
Sorry, missed one in my last commit.  Also, #380 recently removed the link, but
not the actual entry.
=> Fix more broken links.

src/attributes.md
RFC Issue: https://github.com/rust-lang/rfcs/pull/1559
Tracking Issue: https://github.com/rust-lang/rust/issues/34981
Depends on https://github.com/rust-lang/rust/pull/53044.
=> Stabilize 'attr_literals' feature.

src/attributes.md
=> Newline in link refs to fix them

src/items/functions.md
Really small change to correct grammar.
=> Functions.md typo fix

stable-check/src/main.rs
Also made cosmetic improvements to code.
**Blocks https://github.com/rust-lang/rust/pull/57520.**
r? @Centril
=> Removed copyright notices

src/macros-by-example.md
Seems it was forgotten at #468
=> Add missed literal at MacroFragSpec

src/attributes-redirect.html
When these pages were moved during the PR changes, I forgot to update the redirects.
=> Fix attribute redirects.

src/attributes/testing.md, src/crates-and-source-files.md, src/destructors.md, src/expressions.md, src/expressions/block-expr.md, src/expressions/closure-expr.md, src/expressions/loop-expr.md, src/expressions/match-expr.md, src/expressions/method-call-expr.md, src/expressions/struct-expr.md, src/glossary.md, src/interior-mutability.md, src/items/associated-items.md, src/items/constant-items.md, src/items/enumerations.md, src/items/extern-crates.md, src/items/external-blocks.md, src/items/functions.md, src/items/implementations.md, src/items/modules.md, src/items/traits.md, src/lifetime-elision.md, src/macro-ambiguity.md, src/macros.md, src/paths.md, src/procedural-macros.md, src/subtyping.md, src/tokens.md, src/unsafety.md
Verified the output is the same except for the one link in `macros.md` that
I corrected.
=> Remove unused link references.

src/expressions/operator-expr.md
Remove unneeded | from AssignmentExpression
=> Remove unneeded | from AssignmentExpression

src/macros-by-example.md
=> Rust 2015 supports Kleene ? macro operator

src/attributes/limits.md
Updated in https://github.com/rust-lang/rust/pull/62450
=> Update recursion_limit default limit

src/items/unions.md
fix rust-lang-nursery/reference#563
=> Eschew fp lit pattern

src/expressions/await-expr.md
Requested by @Centril in a review on rust-lang/rust#64292.
=> Update await desugaring

src/attributes.md, src/macros-by-example.md
=> Update for "modern" `meta` matcher.

.travis.yml, src/items/generics.md
=> Re-add rust-docs component for lintcheck

src/expressions/array-expr.md
Lint seems to have changed in https://github.com/rust-lang/rust/pull/69185.
=> Update for change in const lint name.

src/attributes/codegen.md
=> Emphasize that `#[inline]` in all shapes is a hint.

src/macros-by-example.md
on Repetitions section. Also did alignment.
=> removed the word "Second" form the beginning of the 2nd list item and  labelled it as `2`

src/items/traits.md
=> Allow trait inner attributes

src/memory-model.md
Various industry -> various industry professionals
=> Fix grammar in memory model 

src/expressions/operator-expr.md
Previously posted on Discord: [#docs](https://discordapp.com/channels/442252698964721669/443492145567891458/764408387705241621).
=> Fix mutable expressions that can be dereferenced

triagebot.toml
=> Enable triagebot

STYLE.md
=> apply #950 to STYLE.md

src/keywords.md
=> added macro_rules to weak keywords

src/expressions/operator-expr.md
=> Add note about the sign of the remainder

src/types.md
fixed: https://github.com/rust-lang/reference/issues/1112
=> keep consistent for primitive types

src/attributes/diagnostics.md
This is meant to resolve #796 
Closes #796
=> #[must_use] on traits also affects trait objects

src/identifiers.md
cc https://github.com/rust-lang/rust/pull/101912
r? @ehuss
=> Update Unicode reference to match rustc implementation

triagebot.toml
These can be helpful for marking status.
=> Enable triagebot shortcuts

src/items/external-blocks.md
Tracking issue for this feature: https://github.com/rust-lang/rust/issues/65815
=> Document the `efiapi` ABI

src/attributes/codegen.md
The f16c feature was stabilized in https://github.com/rust-lang/rust/pull/106323
=> Document f16c target feature

src/items/external-blocks.md
Tracking issue: rust-lang/rust#42202
@rustbot label +S-waiting-on-stabilization
=> Document thiscall abi

src/items/implementations.md
=> implementations.md typo fix

src/items/generics.md
else it [looks](https://doc.rust-lang.org/reference/items/generics.html) kinda off
=> this needs a space

src/attributes.md
See https://github.com/rust-lang/rust/pull/125241
=> Update recognized tool attributes

src/attributes/codegen.md
Companion PR to https://github.com/rust-lang/rust/pull/117468.
Waiting for that to be accepted first.
=> Stabilize Wasm relaxed SIMD

src/comments.md
This adds spec identifiers to comments.md
=> Add spec identifiers to comments.md

src/behavior-considered-undefined.md
This adds spec identifiers to behaviour-considered-undefined.md
=> Add spec identifiers to behaviour-considered-undefined.md

src/conditional-compilation.md
This adds identifier syntax to conditional-compilation.md
=> Add spec identifier syntax to conditional-compilation.md

src/attributes.md
This also allows for the future possibility of `macro_rules`-based
attributes.
=> Clarify that "macro attributes" refers to proc macros

src/type-coercions.md
=> fix typo referring to 'Unsize' trait

src/patterns.md
I noticed this inconsistency here, I hope this is alright that I submit this tiny fix >~<
=> fix inconsistent spacing in example
