src/attributes.md, src/expressions.md, src/paths.md, src/subtyping.md, src/tokens.md, src/types.md, src/variables.md, src/visibility-and-privacy.md
Fixes #3.
This makes all code blocks start with a name recognised by mdbook.
=> Fix code block annotations

src/linkage.md
(part of https://github.com/rust-lang/rust/issues/37406)
=> Add documentation for crt-static

src/visibility-and-privacy.md
See rust-lang/rust#32409
cc @steveklabnik
=> Add pub(restricted) docs

src/SUMMARY.md, src/undocumented.md
Re: #9 
r? @steveklabnik 
CC @chriskrycho
=> Add appendix for list of undocumented features

.gitattributes
This is exactly the same issue as https://github.com/rust-lang/book/pull/549, `x.py test src/tools/tidy` is failing again.
r? @steveklabnik @carols10cents
=> Fix tidy on Windows

src/attributes.md
This is very brief, without any usage or motivation. There's more
information in the 'Testing' section of the Rust Book.
=> Document the `ignore` function attribute.

src/attributes.md, src/macros.md
https://github.com/rust-lang/rust/pull/41295
=> Update Unstable Book links to reflect to new layout.

src/types.md
fixes rust-lang/rust#31137
also technically part of #9
=> document default object lifetime bounds

src/statements.md
A small thing that I noticed while going through the expressions chapter. `unsafe` blocks also have this property, but I'm not sure if they should just be considered another kind of block.
Does this need an example?
=> Explain block like expression statements

src/items.md
I went with "corresponding break" here since you could have a
break that's inside another loop expression for the inner loop
expression, but that wouldn't change the divergence. That probably
needs to be better fleshed out, but I'd leave the fleshing out
of divergence to the loop item section of the reference.
=> Add diverging loops to diverging function section.

src/items.md
Changes this section to make it clear that this is possible.
[RFC 1219 text](https://github.com/rust-lang/rfcs/blob/master/text/1219-use-group-as.md) for reference.
cc #9
=> Document RFC 1219: `use` group `as`

src/items.md
Fix a link; remove the word "Currently". The Rust Reference shouldn't be documenting hypothetical changes, so everything should be "currently".
=> Minor fixes for type aliases

src/expressions.md, src/undocumented.md
And shrink the undocumented list
CC #9
=> Discuss unambiguous function call syntax

src/expressions.md
Documents RFC 1506
RFC: rust-lang/rfcs#1506
tracking issue: rust-lang/rust#35626,
stabilization PR: rust-lang/rust#41145
This PR makes some (small) changes to the `match` section to be able to properly document this feature.
=> Document rfc 1506 - clarified adt kinds

src/items.md
Copy-pasted from https://github.com/rust-lang/rfcs/pull/1897
=> Add union items to the reference

src/type-coercions.md, src/types.md
cc https://github.com/rust-lang/rust/issues/39817
The fcp to stabilize the feature hasn't started yet, but I'm filing anyway, maybe stuff will work faster.
=> Document closure to fn coercion feature

src/expressions.md, src/tokens.md, src/variables.md
This should fix the remaining broken links due to #13. Also makes a reference to temporary variables point to the appropriate section.
=> Fix expr links

src/behavior-not-considered-unsafe.md, src/undocumented.md
=> Add details about integer overflow

src/statements.md
They have no value that can be used in any way, so we cannot talk about the "type of a statement".
=> Statements do not have types.

src/items.md
The "stdcall" ABI only exists on x86, so this causes tests to fail on
other architectures. This should fix rust-lang/rust#40260 next time we
update the reference.
=> ignore doctest of `extern "stdcall"` on non-x86

src/behavior-not-considered-unsafe.md
This explicitly adds leaking of randomized base addresses as not being considered unsafe.
From a discussion on #rust today with @ubsan and @rkruppe
=> Clarify that address leaks aren't considered unsafe

src/behavior-considered-undefined.md
This clarifies that you must access a pointer to violate LLVM's Pointer Aliasing Rules.
From a discussion today on #rust with @ubsan and @rkruppe
=> Clarify that breaking the Pointer Aliasing Rules requires an access

src/attributes.md
Add description of new feature: substitute `{TraitName}` with full path
for the trait implemented in https://github.com/rust-lang/rust/pull/43000.
=> Update description of `rustc_on_unimplemented`

src/items.md
related to https://github.com/rust-lang/rust/pull/42809
=> add associated constants to items reference

README.md
=> Added basic README.md with build instructions

src/comments.md
=> Added grammar of comments

src/attributes.md
=> Added attributes grammar

src/visibility-and-privacy.md
=> Added visibility grammar

src/SUMMARY.md, src/keywords.md
Part of issue #84.
The links to this new page (instead of linking to the [original grammar keywords section](https://doc.rust-lang.org/grammar.html#keywords)) will be corrected in each corresponding section pull request.
=> Added keywords grammar

src/expressions.md, src/items.md, src/types.md
for example, "using a function as an item" does not require any
indirection in any modern rustc. Also try to clarify function items vs.
function pointers.
This could be further improved, but is a start.
=> modernize the function sections in the reference

src/expressions.md
Explain that temporaries created in the condition expression of an `if` or `if`/`else` expression are dropped immediately after the condition expression. Similar for `while`. See rust-lang/rust#12033
=> Document lifetime of temporaries in conditions of if and while-expr

src/items.md
This PR makes (mostly) small improvements to the items chapter
* Make the list at the start of the chapter be in the same order as the actual chapter
* Say some more about C-like enums
* Make the wrapping more consistent (lots of this)
* Fix some header levels
* Make more of the code examples tested
* Be a bit clearer on [RFC 116](https://github.com/rust-lang/rfcs/blob/master/text/0116-no-module-shadowing.md)
* Reorganises the traits section and adds some titles
=> Items chapter cleanup and improvements

src/SUMMARY.md, src/dynamically-sized-types.md, src/interior-mutability.md, src/types.md
Changes to existing sections (first commit):
* Avoid using 'type constructor'
* Give a definition and more complete list of primitive types
* Use 'slice' for the unsized type `[T]`
* Don't use `Vec<T>` in the slice example
* Use the term 'variant', instead of 'variant constructor'
* Remove description of  error E0073 (now removed) when describing rules for recursive types.
* Say some more about references and pointers (including RFC 1135)
* Use `compile_fail` for examples that show compiler errors
* Mention that structs and variants also create function item types
* Try to make it clearer that/why `Fn` can be implemented by `move` closures
* List object safety rules (RFC 255)
* Remove an incorrect statement about which type is the receiver.
Additional sections (second commit):
* Mutable …
=> Types chapter cleanup and new sections

src/attributes.md
It's a useless lang item [which we should remove](https://github.com/rust-lang/rust/pull/44658) so not a good example. There is not drop in replacement because I think it was the only lang item that was just an fn.
=> Remove example mentioning str_eq lang item

src/unsafety.md
Add unions and unsafe traits to the list of unsafe features.
=> Add missing unsafe features

src/tokens.md
=> Add integer literal's grammar

src/tokens.md
=> Add float literal's grammar

src/tokens.md
=> Add grammar for char, string, byte, and raw literals

src/behavior-considered-undefined.md
I tweaked little things in the verbiage of the list before tackling the two open issues on this section.
* Add periods to the end of all list items, even sentence fragments
* Remove the majority of parenteticals and improve flow.
* Add moar links.
* std::ptr::offset doesn't seem to exist? Changed to [`*T::offset`].
* Change link structure so all URLs are at bottom.
* 80 character word wrap except for links.
* Fixes #19.
* Fixes #49.
Note to reviewer: It may be easier to look at each commit individually.
=> Improve Behaviour Considered Undefined section

src/expressions.md
As can be seen [on the AST](https://github.com/rust-lang/rust/blob/51cd06170eccf91a2d93018e939473a8db18da92/src/libsyntax/ast.rs#L1114).
=> The unit value is not a literal, it is a tuple expression

src/expressions.md, src/expressions/field-expr.md, src/expressions/method-call-expr.md, src/expressions/operator-expr.md, src/items/static-items.md
A number of small changes to the expressions section.
* Extend the operator precedence section to be expression precedence (Fixes #107)
* Improve constant expressions (Fixes #120)
* Don't (incorrectly) imply that one can move out of the fields of a boxed struct separately.
* Mention that methods that aren't visible aren't used in type resolution.
* Expressions bound to patterns are always lvalues (so can be unsized) even when moved from.
=> Small fixes to the expressions section

src/identifiers.md
It's misleading to keep XID_Start and XID_Continue on the reference, since they may never be supported in stable.
=> Non-ASCII chars in identifiers aren't supported yet

src/expressions/block-expr.md
=> Blocks grammar

src/items/constant-items.md, src/paths.md
Defines canonical paths, as part of #129.
Note to reviewer(s): There's also two commits that just change the location of links and change where newlines are, so just focus on the giant green blob in the paths file.
=> Canonical Paths

src/expressions/range-expr.md
=> Range expressions grammar

src/SUMMARY.md, src/destructors.md, src/expressions/operator-expr.md, src/glossory.md
=> Document destructors/drop.

src/attributes.md, src/identifiers.md, src/macros.md, src/procedural-macros.md, src/type-coercions.md, src/types.md
The `Compiler Features` section should be moved to the Unstable book.
I've currently commented out the section on Type Coercions because I cannot parse what it's saying right now to check if it's up to date. (Yay, sleepiness.) If anybody else wants to tell me what that is saying, I'd be grateful.
There were two other changes made in this PR, just because I was there. The first is updating what the fake type shown by rustc is for function item types. The second is that I added attributes on unions and added repr to it. This is mainly to make me not forget about unions when I get to making a representations section.
Fixes #119.
=> Remove unstable and 'in the future' things.

src/expressions/closure-expr.md
=> Closures grammar

src/expressions/array-expr.md
Also, add the information that the indexing expressions can be made available in other types by implementing `Index` and `IndexMut`.
Part of #84.
=> Array and indexing grammar

src/expressions/field-expr.md
=> Field access grammar

src/items/enumerations.md
=> Enum grammar

src/items/constant-items.md
=> Constant item grammar

src/expressions/loop-expr.md
=> Loops grammar

src/expressions/if-expr.md
=> If and if let grammar

src/items/enumerations.md
There is no need to reference the C programming language to explain this concept.
=> Rename C-like enum to Field-less enum

src/expressions.md, src/interior-mutability.md, src/items/constant-items.md, src/items/static-items.md
AFAIK, this was stabilized in what is currently beta, so the reference will be out of date for six weeks.
I'm not entirely happy with what I've written, but I'm also not altogether happy with how the static and const sections are currently written, and will go back at some point to organize them a bit better. Likewise with destructors.
=> Document RFC 1440.

src/glossary.md, src/items/implementations.md
Trying to not focus on what it means to associate a type, nor deal
too much with generic impls at this point. Those will come in future parts.
Right now everything about associated types are defined in `items/traits.md`. I didn't touch that here.
Fixes #5. Albeit, I'm not a fan of the wording which I just pulled directly from the RFC.
cc @scottmcm for review.
=> Implementations improvements part 1

src/expressions.md, src/expressions/array-expr.md, src/expressions/block-expr.md, src/expressions/field-expr.md, src/expressions/match-expr.md, src/expressions/method-call-expr.md, src/expressions/operator-expr.md, src/expressions/path-expr.md, src/expressions/struct-expr.md, src/glossary.md
This effort is already underway in the compiler as well, and this is the only other place we talk about these two kinds of expressions.
I also moved a lot of links down to the bottom of the page. I already painstakingly checked that every link was correct.
=> Rename lvalue and rvalue to place and value expressions

src/SUMMARY.md, src/attributes.md, src/dynamically-sized-types.md, src/glossary.md, src/items/enumerations.md, src/type-layout.md, src/types.md
r? @scottmcm @Gankro @eddyb - Though if you don't want to, just say so and unsubscribe from the thread.
There's no good term for what the compiler calls ADTs - structs, enums, and unions. I cannot think of one either. As such, there's a *FIXME* in there.
I'm also choosing a very conservative definition of type layout. I'm not sure if it should be expanded or not, or if the valid values and calling convention changes should be a part or not. Although I don't think they should, I don't have any logical arguments either way. Part of the problem is that layout can probably mean multiple things at the same time. E.g. Layout for allocators is just size and alignment.
=> New Section - Type Layout

src/expressions/method-call-expr.md
For example, this is allowed:
```rust
fn f<T: ::std::ops::Deref>(t: T) {
t.deref();
}
```
=> Type parameters have slightly different method resolution

src/SUMMARY.md, src/dynamically-sized-types.md, src/expressions.md, src/expressions/array-expr.md, src/expressions/closure-expr.md, src/expressions/field-expr.md, src/items/constant-items.md, src/special-traits.md, src/special-types-and-traits.md, src/the-copy-trait.md, src/the-deref-trait.md, src/the-drop-trait.md, src/the-send-trait.md, src/the-sized-trait.md, src/the-sync-trait.md, src/types.md, src/unsafety.md
Moves this all into one page. Expands this section to document special types as well.
Doesn't change the wording much for the traits that already had pages.
Uses the nomicon pages for variance (for now) and dropck.
This does break a 2 links in std that should really point to the documentation for method name resolution, PR for that soon.
cc rust-lang/rust#44496 (RFC 2133)
Things that aren't lang items, but do appear here:
* `Send`, `Sync`, `UnwindSafe` and `RefUnwindSafe` being auto traits (can probably be removed if/when auto traits are stabilised)
* ~~`Send` and~~ `Sync` being used for thread safety
* `Box` being `fundamental` (will link to text in #146 once that's merged)
Lang items that don't appear here:
* `Debug`: this is used for the missing debug lint.
* `drop_in_place`: not …
=> Reorganise the special traits section

src/special-types-and-traits.md
This was added by the PR I just approved, since I didn't want to wait another cycle between editing and reviewing when this PR would be faster to make.
=> Remove unused link reference.

src/attributes.md
Fixes #92 
r? @QuietMisdreavus
=> Link to the rustdoc book for doc attribute docs.

src/paths.md, src/statements.md
Fixes #25.
Also, given https://github.com/rust-lang/rust/issues/45251, I removed the part where whether outer-level control flow expressions are expression statements without semicolons depends on what the expression evaluates into.
=> Better describe the scope of items defined in item declaration statements

src/statements.md
See https://play.rust-lang.org/?gist=59090cd71dfbd84cbbdc611b94a0a9c2&version=stable for an example that shows that the rule explained in the current docs is incorrect. It implies that the parse ambiguity is resolved depending on the type of the control flow expression, but that's not true.
=> Clarify implicit semicolon ambiguity resolution.

src/glossary.md, src/items/traits.md, src/types.md
=> Better document trait objects.

src/expressions/method-call-expr.md, src/types.md
1. While it's "obvious", it should be stated that trait objects actually
implement the traits they are for.
2. Added lifetime bounds to the syntactical description and aliasing
rules of trait objects. I'm not sure if the aliasing part is correct.
3. Added a big fat warning to the method call expression about trait
objects having an inherent impl define a method with the same name
as one of the methods the trait object has from the trait. I
think that trait objects following different rules than other types
should be changed.
=> Moar trait object verbiage.

src/expressions/method-call-expr.md, src/type-coercions.md
As a part of this, remove the reference to coerce_inner and replace it
with a proper description of unsized coercions. That description will
have to be updated later when more of the unsized work stabilizes.
Please review this for correctness; I was mostly working off of the description in #62, the [DST RFC](https://github.com/rust-lang/rfcs/blob/master/text/0982-dst-coercion.md), and some personal test examples.
And of course, if there's anything that can be done to include clarity (such as more examples), I can do that too.
=> Adjust receiver lookup to match the actual impl

src/behavior-considered-undefined.md
A follow-on to https://github.com/rust-lang-nursery/reference/pull/196
=> remove unwinding from UB

src/attributes.md, src/type-layout.md
Updated reference for stabilization of the `#[repr(align(x))]` attribute. See tracking issue comments https://github.com/rust-lang/rust/issues/33626#issuecomment-348467804 for discussion.
=> Documented the `#[repr(align(x))]` attribute.

src/undocumented.md
Small edit, this feature was documented #41, I forgot to remove it from undocumented.md.
=> Remove chained comparisons from the undocumented page.

src/items/use-declarations.md
The feature `use_nested_groups` will soon be stabilized, and this PR adds a mention of it in the reference.
This only adapts the current reference to be coherent with the new implementation, but it doesn't add a dedicated section about it. If that's something we want I can work on it (but I don't think it's really needed).
This fixes #225, tracking issue rust-lang/rust#44494
=> Add mention of RFC 2128 (use_nested_groups) in the reference

src/expressions/match-expr.md
=> Add match expression syntax and document feature(match_beginning_vert)

src/expressions/match-expr.md
According to the Rust book, the word "scalar types" means ["integers, floating-point numbers, booleans, and characters."](https://doc.rust-lang.org/book/second-edition/ch03-02-data-types.html#scalar-types)
However, range patterns don't work on booleans.
(No one would actually use range patterns on booleans, of course.)
=> Clarify which types range patterns work on

src/items/structs.md
=> Struct grammar

src/SUMMARY.md, src/items/associated-items.md, src/items/functions.md, src/items/traits.md, src/types.md
Because they are a cutting concern between impls and traits, they don't really fit in either.
If anybody has concrete suggestions for how to make this better, I'm all ears. I'm not a fan of a lot of my writing in this PR. Especially the definitions.
=> Move associated items to their own page.

src/items/associated-items.md
Hides lines to avoid unmatched close brace and extra blank lines.
Follow up to #214
=> Hide more lines in code example

src/attributes.md
`[Compiler plugins][unstable book plugin]` is now a link again. See #250
=> fixes #250

src/types.md
This PR more fully documents closure types, including the mechanics of captures and the traits implemented by them. I intend to work on closure expressions as well, either in this PR or a follow-up, but felt this was a good place to put them.
I didn't fully explain capturing here, as I feel like that's better for closure expressions. The bit about no field captures might make more sense there as well, but I think the mechanics of how captures are typed and the implications on the traits belong here.
This PR is written for a post-[RFC 2132](https://github.com/rust-lang/rfcs/blob/master/text/2132-copy-closures.md) world, where closures have `Clone` and `Copy`, and intended as part of the stabilization docs for that RFC. The tracking issue is rust-lang/rust#44490. That bit could easily be …
=> Improve documentation on closure types.

src/identifiers.md, src/macros-by-example.md, src/tokens.md
Separate identifiers, and keywords including identifiers in the grammar.
=> Split identifiers from keywords or identifiers

src/SUMMARY.md, src/items/constant-items.md, src/items/static-items.md, src/lifetime-elision.md, src/types.md
Second PR to add documentation for lifetimes (next will probably moving the relevant parts of the NLL RFC text into the reference when it gets stabilised).
This is mostly existing documentation from the nomicon/reference. Significant changes from that documentation:
* Don't talk about possible future changes (elision in `impl` headers)
* Be more concise in the description of function lifetime elision
* Add an example of function pointer and function trait elision
* Note that `'static` is the preferred bound in trait objects with multiple bounds:
```rust
trait A<'x, 'y>: 'x + 'y {}
impl A<'a, 'static> {} // A<'a, 'static> + 'static
```
* Don't say anything about the case in rust-lang/rust#47078
* `const RESOLVED_STATIC: &Fn(&Foo, &Bar) -> &Baz` is invalid, not inferred with `'static` …
=> Lifetime elision

src/keywords.md
* List places where keywords are not allowed
* Move reserved keywords up a section (as they're closer to strict keywords than weak keywords)
* Don't list `box` as a strict keyword for now
* Don't list `catch` and `default` as reserved keywords for now, as they're not used in stable Rust.
=> Revise keywords page

src/expressions/operator-expr.md
=> Operator expressions grammar

src/theme/reference.css
Color links containing inline code the same as normal links. Use the CSS found in the [Cookbook](https://github.com/rust-lang-nursery/rust-cookbook/blob/master/theme/custom.css).
cc rust-lang-nursery/mdBook#537
=> Color inline code links

src/SUMMARY.md, src/expressions.md, src/expressions/grouped-expr.md, src/expressions/operator-expr.md
and added another example of its use.
Should I remove this bit ```This operator cannot be overloaded.```? It is not really an operator.
=> Moved grouped expressions to its own page

src/expressions/match-expr.md
- added MatchArms to make things clearer
- added attributes to both the match block and match arms
- removed pipes before the patterns, since they're experimental
=> Fixes for the match grammar

src/expressions.md, src/expressions/match-expr.md, src/expressions/range-expr.md
Provides the reference documentation for rust-lang/rust#28237.
=> Document inclusive ranges.

src/tokens.md
This is already in the summary table above.
=> Document the <=0x7F restriction on \x escapes.

src/expressions/match-expr.md, src/items/use-declarations.md
Those break mbook's parsing sometimes.
=> Fixed non-escaped *s in grammar

src/items/static-items.md
Removed inlining guarantees as they are false e.g. in the case of using a non-mutable static integer. Added "Non-`mut`" to the statement about read-only memory. Removed the parenthesis about binding `C` statics. Added a link to destructors where it says "drop".
=> Statics may sometimes inline.

src/items/implementations.md
You should double check, but I think this was wrong. It seemed odd to me.
=> Fix grammar for orphan check

src/expressions.md
* Clarify associativity refers to grouping of operators, not evaluation order.
* Remove unstable operators.
=> Fixes for operator precedence

src/attributes.md, src/type-layout.md
* [Rendered](https://havvy.net/rust-reference/attributes.html)
* [Tracking Issue](https://github.com/rust-lang/rust/issues/43302)
* [RFC](http://rust-lang.github.io/rfcs/1940-must-use-functions.html)
* [Unstable Book Docs](https://doc.rust-lang.org/nightly/unstable-book/language-features/fn-must-use.html)
This is the reference side of documenting this attribute &mdash; both the updates for the RFC and the original functionality. I do not think that this PR is sufficient documentation for stabilizing the feature, as I think the API guidelines should also be updated.
=> Document RFC 1940 (must_use on fns)

src/SUMMARY.md, src/special-types-and-traits.md, src/subtyping.md
First of a few PRs to improve the documentation of lifetimes in the reference. Based on the documentation in the Nomicon.
cc #9 (rust-lang/rfcs#738)
=> Document variance

src/types.md
When I wrote this, for some reason I thought that references are always
Sync.
=> Correct when closures are Sync.

src/special-types-and-traits.md
=> Clarify semantics of auto traits.

src/types.md
Also remove copy from the main list of permissible captures, since copy
only occurs when `move` is specified.
=> Add explanation of unique immutable borrows.

src/attributes.md
The current definitions mean that the following are valid attributes:
- `#[foo(,)]`
- `#[foo(, , , , ,)]`
These aren't (intended to be) valid. This fixes the definitions to only allow an EMPTY at the end of a comma-separated list.
=> Fix the definition of MetaItem and MetaSeq

src/crates-and-source-files.md
Also updated a link for attributes and changed the first paragraph to a note.
=> Document restrictions of the main function

src/items/traits.md, src/types.md
Some of it feels like it was from the guide. Should all be referency now. And also more cross linking.
=> Improve supertraits documentation

src/types.md
When reading this I wondered whether those two are Rust types I've never heard before. This PR removes the code formatting style in favor of simple double quotes.
=> Wrap binary32 and binary64 in quotes

src/tokens.md
Various minor fixes and additions.
=> Fixups for token ref

src/expressions/operator-expr.md
Various small fixes and additions.
=> Fixups for operator ref

src/tokens.md
Additionally all other tokens were sorted `u..` first, then `i..` - so I re-ordered `usize` & `isize` to conform
=> Add u128 and i128 tokens

src/attributes.md, src/items/generics.md
Attributes in generics is stabilized in 1.27 as per https://github.com/rust-lang/rust/pull/48851/.
I moved the defining italics for attributes to the actual definition and gave inner/outer attributes actual definition lines instead of leaving it implied.
There's also a few newlines for 80 character style and removing trailing spaces in here.
=> Attributes in generics position and general attributes improvements

src/attributes.md
This should be easy to review.
=> Remove 'main' attr from reference. Still unstable.

src/lifetime-elision.md, src/trait-bounds.md
cc #278 There don't seem to be any cases where `'_` could be used outside of this chapter.
`'_` can also be used for inferred lifetimes, but I don't think there is any documentation for them yet.
Also uses dyn trait in the elision chapter (cc #279)
=> Document underscore lifetime elision

src/types.md
This was fixed by me in https://github.com/rust-lang/rust/pull/51276 so one less warning needed in the reference.
=> Remove auto traits not deduped warning

src/expressions/array-expr.md
* const_err is now deny-by-default (not sure how this didn't get noticed by Rust's CI)
* Indexes are checked on non-const arrays.
* Fix some typos
=> Update array expressions

src/visibility-and-privacy.md
_This equivalent_ -> _This is equivalent_
I have re-wrapped the line as it was too long after the added "is".
=> Fix grammar in the "Visibility and Privacy" section

src/expressions/method-call-expr.md, src/theme/reference.css, src/trait-bounds.md, src/type-layout.md, src/types.md
I want warnings to stand out more, so why not give them their own CSS?
I'm not quite sure what this looks like when there's no font that handles the warning sign character, but as long as it's not terrible, it should be fine? It's mostly there for decoration. cc @alercah for having a Linux box that has said lack of font.
=> Warning css

src/statements.md, src/variables.md
This gets rid of the `and/or` in the "`let` statements" section and gives an example showing that Rust tracks initialization of variables for uses.
=> Improve verbiage around let statements and variable initialization

src/attributes.md, src/expressions/block-expr.md, src/expressions/match-expr.md, src/items/functions.md, src/items/implementations.md, src/statements.md
Each commit does its own small thing.
This builds on top of #350, so merge that before taking a look at this.
=> General attribute docs improvements

src/expressions/closure-expr.md, src/types.md
I always have to open RFC 231 to check when i need to explain these rules to others 
So i copied these text (with minimal editorial changes) from RFC 231 to The Rust Reference so people can read them more easily.
=> [RFC 231] Capture mode and closure trait rules

src/destructors.md
https://github.com/rust-lang/rust/pull/52711 changes `ManuallyDrop` from a union to a struct, so the link needs to be updated.
=> fix link to ManuallyDrop

src/expressions/match-expr.md
=> Document interaction of `|` patterns and pattern guards

src/undocumented.md
About removals:
* Attributes on match arms was documented by me last time I looked at attributes.
* UFCS a.k.a. diambiguating function calls is documented on the call expression page.
* unaligned access appears to just be library things
=> Add impl trait and remove others from undocumented list

src/SUMMARY.md, src/attributes.md, src/conditional-compilation.md
Purposely not touching the content in this PR. I feel like this is a concept that deserves its own page and not to just be hidden in the attributes section.
=> Move conditional compilation to its own page

src/memory-model.md
I think this is better than the previous page, what do you all think?
=> admit we don't have a memory model

src/behavior-considered-undefined.md
`linkchecker` complains about those.
=> Don't use directory link

src/tokens.md
`linkchecker` doesn't like absolute paths.
=> Make absolute path relative

src/attributes.md
Fixes #349 
Went and did this because it's been two months without a response.
=> Add optimization hints section to attributes

src/type-layout.md
=> Document transparent representation

src/expressions/block-expr.md
1. Don't consider semicolons part of the statement. As per the
`stmt` macro matcher, they're not a part of it. They are a part
of the block expression though, so the grammar is updated to
show that.
2. Try to better describe what a block expression is. By saying
it's like a module, we're probably confusing people.
3. Show an example of using a block expression to force moving a
value out of a variable. I personally didn't understand what
that fully entailed until I wrote the example.
4. Link to the unsafety section instead of redescribing what
unsafe is allowed to do in the unsafe block section.
=> Expand block expression section

src/identifiers.md, src/tokens.md
Lifetimes (and labels) don't support raw identifiers.
=> Fix lifetimes with raw identifiers.

src/attributes.md, src/crates-and-source-files.md
cc @QuietMisdreavus and @steveklabnik for possibly out-of-scope documentation here.
=> Test attributes deserve their own section

src/types.md
I added a section about the `bool` type in  [types.md](https://github.com/rust-lang-nursery/reference/blob/master/src/types.md). This resolves #238.
=> Added bool type section

src/attributes.md, src/expressions/block-expr.md, src/expressions/match-expr.md, src/items/functions.md, src/items/implementations.md, src/statements.md
This is blocked on #381 and #382 for correct links.
1. The main task of this PR is to show which attributes are allowed on functions.
2. I renamed the "`must_use` Attribute" section to `must_use` to match the "`derive`" section further on in the page.
3. Updated links to the `cfg` attribute to the new conditional compilation page. Probably should have done this when moving `cfg` to its own page. But doing it here where I'm adding a new link to it.
=> Attributes on functions

src/macros-by-example.md
=> Stabilize macro_vis_matcher

src/introduction.md
Fixes #406 
I totes stole the section title "How to Use This Book" from TRPL. ❤️ 
This PR will be easier to read by the individual commit.
Due to rendering being important, I have updated my website to render to this commit. [Rendered](https://havvy.net/rust-reference/introduction.html)!
=> Improve Introduction

src/trait-bounds.md
=> Put lines in correct order

src/expressions.md
=> the originally -> originally

src/expressions/if-expr.md, src/expressions/loop-expr.md
=> Document desugarings that happen when creating hir

src/SUMMARY.md, src/expressions/closure-expr.md, src/expressions/if-expr.md, src/expressions/loop-expr.md, src/expressions/match-expr.md, src/items/functions.md, src/macros-by-example.md, src/patterns.md, src/statements.md, src/tokens.md
This is a repost of #284, rebased, updated, most review comments addressed, and some additional information added.
Closes #83, #300, #301.
This adds a small description of binding modes which covers #280, but I'm not confident it is detailed enough to consider it complete.  There are a lot of details not covered in depth (like const references).
=> Patterns chapter

src/introduction.md, src/items/associated-items.md
cc @Centril @steveklabnik  https://github.com/rust-lang/rust/issues/41686
=> Add note about anon params

src/macros-by-example.md
cc rust-lang/rust#51934
The new Kleene op is not stable yet, but the removal of `?` as a separator is. I can split this up into two PRs if you want.
=> Add some notes on  repetition

src/expressions/struct-expr.md
This includes some rework and expansion of the contents.
=> Grammar: Add struct expression.

src/expressions/if-expr.md
Part of rust-lang/rust#53668.
cc @centril
=> Mention syntax ambiguity for eRFC 2947.

src/items/associated-items.md, src/items/external-blocks.md, src/items/functions.md, src/items/implementations.md, src/items/traits.md, src/unsafety.md
These all are intertwined with the "function" definition. Updates grammar for:
- Functions and methods
- Extern blocks
- Implementation
- Traits
=> Grammar: Functions, methods, impl, traits, extern.

src/SUMMARY.md, src/const_eval.md, src/expressions.md, src/items/functions.md
tracking issue: https://github.com/rust-lang/rust/issues/53555
=> Document const functions

src/const_eval.md, src/expressions/array-expr.md, src/items/associated-items.md, src/items/enumerations.md, src/items/functions.md, src/items/traits.md, src/types.md
This PR does 7 things:
1. Capitalize lists.
2. Define const function with italics.
3. Call extern and const qualifiers. We may want to look at calling pub a qualifier as well.
4. Fix enum discriminants to say they take a constant expression.
5. Explain that const functions have restrictions more tersely.
6. Fix link to constant expressions on array literal page.
7. Move attributes on functions back down to the bottom of the page.
8. Rename `FunctionFront` to `FunctionQualifier` in the grammar as well.
The first six are in the first commit. The last two are in their own commit.
=> Const function

src/attributes.md
Being stabilized in https://github.com/rust-lang/rust/pull/54870 , wanted to preserve some documentation. Clippy has more docs on this.
r? @steveklabnik
=> Mention tool lint attributes

src/attributes.md, src/crates-and-source-files.md, src/items/functions.md, src/items/modules.md
I set out to document `no_std` and ended up documenting preludes in general. This also led to the removal of the "Module-only attributes" section as one of its attributes was placed in the prelude attributes section while the other attribute is already documented pretty well on the modules page, so I just linked to it from the attributes page. I wanted to get rid of that section anyways. This means the only two sections in the attribute sections that need to be removed are "crate only attributes" and "misc. attributes". Though having all the sections subsumed under misc attributes was a mistake, and they need to be brought a level higher. I'll do that after this lands, while also sorting them alphabetically.
I am generally happy with the new prose I've written in this PR. I specifically …
=> Document preludes

src/procedural-macros.md
1. `'` -> `"`
2. `parameter name` is not right, input is `input`, but `item` is used
3. link for `[union]` is not existed, it should be `[unions]` (in the last line of that file)
=> Fix typo in a procedural-macros example.

src/procedural-macros.md
The 3rd paragraph in [Derive mode macros](https://doc.rust-lang.org/nightly/reference/procedural-macros.html#derive-mode-macros) missed a link.
=> Add a missing link.

src/crates-and-source-files.md, src/items/extern-crates.md
Stabilization PR: https://github.com/rust-lang/rust/pull/54403
=> `extern crate` changes.

src/items/external-blocks.md, src/unsafety.md
Also includes some small improvements to the extern blocks explanation
=> Note additional things as unsafe

src/type-layout.md
I documented the size behavior of type `str` to the 9.3.Type Layout section.
Fixes #410
=>  Document type layout of `str` #410 

src/conditional-compilation.md
[Rendered](https://havvy.net/rust-reference/conditional-compilation.html)
Fixes #384 
Partial r? @ehuss for grammar additions.
I put a couple questions into comments into the source itself.
I also wonder if making each configuration option set by the compiler its own section like I did is too spacey. I could bring it back down into a list if y'all agree with that.
=> Referenceify conditional compilation

src/items/generics.md, src/items/traits.md, src/items/use-declarations.md
- `trait` was missing bounds.
`trait T: Clone {}`
- Type for `const` in trait is not optional.
```rust
trait T {
const C = 1;  // INVALID
const C2: i32 = 1;
}
```
- Associated type in trait can have a bare `:`:
`trait T {
type X:;
}`
- Visibility is not needed on UseDeclaration, it is part of Item.
- `:` in generic lifetime param was missing parenthesis grouping to make it optional.
`fn f<'a>() {}`
=> Fix some grammar issues.

src/crates-and-source-files.md, src/items/modules.md
Stabilization PR: https://github.com/rust-lang/rust/pull/54072
Tracking issue: https://github.com/rust-lang/rust/issues/53125
Part of [RFC 2126](https://github.com/rust-lang/rfcs/blob/master/text/2126-path-clarity.md).
=> Document mod.rs changes.

src/attributes.md
Both make their way to LLVM without problems today. Putting attributes on expressions is mostly still unstable, but can be worked around thanks to https://github.com/rust-lang/rust/issues/32796, so it's possible to rely on this in stable code.
=> Mention that #[cold] and #[inline] work on closures

src/crates-and-source-files.md, src/expressions/closure-expr.md, src/input-format.md, src/introduction.md, src/notation.md
Now that the reference includes the complete grammar, I think the last remaining references to the old grammar can be removed. This includes a few different changes (I can split these up if you'd like):
- Remove some references to the old grammar's rule names.
- Remove the link to the old grammar.
- Fix a bug with the _ClosureExpression_ rule which didn't correctly allow for untyped parameters. Also rewrote some of the closure text when removing the old rule names.
- Remove some of the grammar descriptions that only applied to the old grammar.
- Added a brief description of the notation based on some unfinished work by brauliobz.
=> Remove the last remnants of the old grammar.

src/macros-by-example.md
This feature will soon stabilize in https://github.com/rust-lang/rust/pull/56072.
=> Mention the literal macro matcher

src/macros.md
The previous introduction to macros incorrectly stated the purpose of macros in Rust.  I modified the intro to more appropriately introduce this feature.
Fixes #152
=> corrected introduction to macros in macros.md

src/items/functions.md
Before, the `[const context]` link on line 149 was broken (expand the collapsed section of the diff to see it), and the wording on line 153 was incorrect. Now, they're fixed. I also made the link target more specific (directing to the correct section on the *Const evaluation* page).
Fixes https://github.com/rust-lang-nursery/reference/issues/476.
=> Fix minor typos in const functions section

src/visibility-and-privacy.md
When updating paths, I neglected to add a note that visibility paths must
be absolute.
=> Update pub(in path) for 2018.

src/items/functions.md
=> Update `unsafe` in const functions documentation

src/patterns.md
Range patterns may now be irrefutable, as of `exhaustive_integer_patterns`.
Fixes #472.
=> Update range pattern refutability

src/items/extern-crates.md, src/items/use-declarations.md
Closes #470.
This includes a semi-unrelated change to `use` documentation to clarify some changes regarding `use cratename`. I'm not super comfortable with these changes, but I don't see anything obviously wrong.
=> Document underscore imports.

.travis.yml
Travis has pretty good support for caching rust builds now by store the .cargo directory.  This would enable this build to rebuild mdbook every time.
From [my test], it looks like the average build time will go from ~10 minutes to ~1 minute.
The one potential downside to this is mdbook won't be rebuilt with new nightly versions of Rust.  Presumably this doesn't matter though since the version of mdbook is pinned, and upgrading it would require running one build with `cargo install --force --version =<new-version>`, and then removing the `--force` again (otherwise it would always rebuild and thus remove the point of caching it). It doesn't seem like the version of mdbook is getting updated regularly though so this seems like it shouldn't be too big of a burden.
[my test]: …
=> Use mdbook release binary

src/const_eval.md
=> "Improve language in 'Constant Expressions'.

src/expressions/loop-expr.md, src/expressions/match-expr.md, src/expressions/struct-expr.md, src/glossary.md, src/patterns.md
This PR renames *"__head__ expression"* wrt. `match` and such to *"__scrutinee__ expression"* as is typical in various languages with pattern matching (e.g. [Haskell](https://downloads.haskell.org/~ghc/7.6.2/docs/html/users_guide/informal-semantics.html), [OCaml](https://caml.inria.fr/pub/docs/manual-ocaml/extn.html#sec252), [Idris](https://www.idris-lang.org/idris-0-9-11-released/), [Agda](https://media.readthedocs.org/pdf/agda/v2.5.3/agda.pdf), [Scala](https://issues.scala-lang.org/browse/SI-7171), and [ML](https://samth.github.io/match-ifl-full.pdf)).
=> "head expression" => "scrutinee expression"

src/attributes.md, src/items/extern-crates.md
Stabilized in 1.31.
- Tracking issue: https://github.com/rust-lang/rust/issues/55599
- Stabilization PR: https://github.com/rust-lang/rust/pull/56032
- Implementation PR: https://github.com/rust-lang/rust/pull/54658
Closes #466.
=> Document extern_crate_item_prelude

src/const_eval.md
=> Let bindings are now available in const contexts

src/items/unions.md, src/types/union.md
=> unions have no active field

src/expressions.md, src/expressions/struct-expr.md
=> Clarify what access struct updates do

src/const_eval.md
The links to operator-expr.html were broken. Also a little bit of cleanup
(mainly just sorting the link list).
=> Fix some broken links.

src/expressions/if-expr.md, src/expressions/loop-expr.md, src/expressions/match-expr.md
=> Document if_while_or_patterns

src/items/extern-crates.md
=> Document extern_crate_self

src/expressions/operator-expr.md
Closures that capture local variables shouldn't be able to cast to function pointers, should they?
=> Fix an incorrect note

src/items/generics.md, src/items/implementations.md
These are a few edits to phrases that I found hard to understand on my first reading.  I believe I've preserved the same meaning (to the best of my understanding!).
=> Clarifications

src/attributes.md, src/procedural-macros.md
This is just my personal preference, which seems to read more easily to me. The concept of "mode" wasn't really clear, and I think "derive macro" is sufficient.
For context, see: https://github.com/rust-lang-nursery/reference/pull/412#discussion_r214538427 and https://github.com/rust-lang-nursery/reference/pull/528#pullrequestreview-209855431
=> Remove "mode" from derive macro terminology.

src/conditional-compilation.md
`target_has_atomic` is not stable, and it's not clear to me if it ever will be. See https://github.com/rust-lang/rust/issues/56753 for more context.
=> Remove target_has_atomic.

src/attributes.md, src/conditional-compilation.md, src/macros-by-example.md, src/procedural-macros.md, src/type-layout.md
- Document `unrestricted_attribute_tokens`, closes #525
- Document `tool_attributes`, closes #526
- Document `cfg_attr_multi`, closes #500
- Remove `linked_from`, it was removed in https://github.com/rust-lang/rust/pull/37973/
- Remove `macro_reexport`, it was removed in https://github.com/rust-lang/rust/pull/49982/
- Remove unstable attributes: `linkage`, `link_args`
=> Update attribute documentation.

src/items/unions.md
Link does not work when part of the book suite on rust-lang/rust.
=> Fix broken link.

src/procedural-macros.md
Previously:
```rust
fn invoke1() {}
// out: attr: ""
// out: item: "fn invoke1() { }"
fn invoke2() {}
// out: attr: "bar"
// out: item: "fn invoke2() {}"
fn invoke3() {}
// out: attr: "multiple => tokens"
// out: item: "fn invoke3() {}"
fn invoke4() {}
// out: "delimiters"
// out: "fn invoke4() {}"
```
Added missing `attr` and `item`
=> Fix copy-paste error in procedural-macros.md

src/behavior-considered-undefined.md
Fixes #485 
I just wrote this up in a few seconds, so not sure how good the writing is. Figured a note would be good for undefined behavior crossing language barriers.
r? @RalfJung or @ubsan
=> Note that UB is program-global

src/SUMMARY.md, src/appendices.md, src/attributes.md, src/items/extern-crates.md, src/items/modules.md, src/macro-ambiguity.md, src/macros-by-example.md
The primary motivation here was to increase clarity and fully address the
scoping and naming details. The inclusion of RFC 550's formal specification is
to move it to the reference where it can be updated. I made several changes,
motivated by accommodating `?` and new fragment specifiers, but there are some
other things which need highlighting so that they can be double-checked for
correctness.
* Permit the empty string to follow on in the first invariant; this is a
technical oversight in the definition I believe.
* Added a requirement that repetitions obey the follow rules; this was an
oversight in the original RFC and currently planned for fix.
* Rewrote the definition of FIRST for complex NTs to be more clear.
* Added a case to LAST for `?` repetitions
* Removed the last example of …
=> Expand docs on Macros By Example.

.travis.yml, src/items/unions.md, tests/linkcheck.sh
This is a little gumby, but it works.
It:
- Downloads linkchecker from rust-lang/rust.
- Copies the HTML pages from nightly rustup, which should be a close reflection of how they look on doc.rust-lang.org.
- Build and copies the reference.
- Runs the linkchecker.
=> Add linkchecker.

src/attributes.md, src/attributes/codegen.md, src/behavior-considered-undefined.md, src/conditional-compilation.md, src/linkage.md
- Stabilization PR: https://github.com/rust-lang/rust/pull/49664
- [RFC 2045](https://github.com/rust-lang/rfcs/blob/master/text/2045-target-feature.md) `target_feature` and `cfg_target_feature`
- Tracking issue: https://github.com/rust-lang/rust/issues/44839
- Tracking issue `cfg_target_feature`: https://github.com/rust-lang/rust/issues/29717
- [RFC 2325](https://github.com/rust-lang/rfcs/blob/master/text/2325-stable-simd.md) Stable SIMD
- Tracking issue: https://github.com/rust-lang/rust/issues/48556
Closes #286
=> Document `target_feature` and `cfg_target_feature`.

src/attributes.md, src/attributes/limits.md
=> Document `type_length_limit`.

CONTRIBUTING.md, src/introduction.md
- Drop IRC, there doesn't seem to be any traffic there. Link Discord.
- Clarify the reference tracks stable-on-nightly (if that makes sense).
- Remove the RFC review process, it is no longer true (#9 is closed).
- Update stabilization process to something that is closer to reality.
=> Some minor contributing updates.

tests/linkcheck.sh
Can't merge upstream with line length >100. 🙃
=> Fix tidy error.

src/items/external-blocks.md
Stabilization PR: https://github.com/rust-lang/rust/pull/52445
Tracking issue: https://github.com/rust-lang/rust/issues/52090
=> Document wasm_import_module for #[link].

src/expressions/match-expr.md, src/expressions/operator-expr.md, src/special-types-and-traits.md, src/type-coercions.md, src/type-layout.md, src/types/trait-object.md, src/variables.md
=> Typo fixes

src/type-layout.md
Closes #483
I feel like this is lacking, but I'm not sure what else to add.
=> Document repr packed(N).

src/items/implementations.md
Not sure if this is optional, but text bellow states that this is optional for _trait implementation_ and for _inherent implementation_ it's not clear.
=> Added missing ? to Generics from InherentImpl and TraitImpl

src/procedural-macros.md
There is an example in `procedural-macros.md` that doesn’t compile:
```
Compiling proctest v0.1.0 (/nowhere/proctest)
error[E0308]: mismatched types
--> src/lib.rs:42:50
|
42 | pub fn derive_helper_attr(_item: TokenStream) -> TokenStream {
|        ------------------                        ^^^^^^^^^^^ expected struct `proc_macro::TokenStream`, found ()
|        |
|        this function's body doesn't return
43 |     TokenStream::new();
|                       - help: consider removing this semicolon
|
= note: expected type `proc_macro::TokenStream`
found type `()`
```
This PR fixes the example so that it compiles.
=> Fix example code of derive macro

src/tokens.md
Closes https://github.com/rust-lang/rust/issues/60494
=> Document that literals with any suffixes are valid as tokens

src/conditional-compilation.md
Bitrig support has been removed (by me) in https://github.com/rust-lang/rust/pull/60775
=> Bitrig support has been removed

src/macros-by-example.md
It does not compile with the semicolon.
=> Fix typo in lazy_static example.

src/type-layout.md
Closes https://github.com/rust-lang/rust/issues/57996
Stabilization report: https://github.com/rust-lang/rust/pull/61229#issuecomment-496092471
r? @ehuss
=> Describe `#[repr(align(x))]` semantics on `enum`s

src/items/constant-items.md
Closes https://github.com/rust-lang/rust/issues/54912.
Stabilization report: https://github.com/rust-lang/rust/pull/61347#issuecomment-497533585.
r? @ehuss
=> Document `underscore_const_names`

src/conditional-compilation.md
The restriction for `cfg` on generic parameters was removed recently in https://github.com/rust-lang/rust/pull/61547.
=> Update for cfg on generic parameter.

src/items/unions.md, src/types/union.md
@gnzlbg we *do* guarantee offset 0 for `repr(C)`, right? That just follows from being C-compatible?
=> unions: call out field offset issues

src/attributes/limits.md
There was an extra left parenthesis on the demo code for the `type_length_limit` attribute.
The code snippet isn't supposed to compile but produced the wrong error.
Edit: The snippet now _compiles_ when it isn't supposed to; I think we should open a separate issue?
=> Remove extra parenthesis

src/expressions/struct-expr.md, src/items/modules.md, src/linkage.md
A few that have slipped through the cracks.
=> Fix some links.

src/items/modules.md
The last paragraph in the modules section talks about attributes on modules.  It then says, "The built-in attributes that have meaning on a function are ...", and lists attributes such as `#[path]` that work on modules.
This changes it to "The built-in attributes that have meaning on a module are ..."
=> Fix a type in the modules section: functions => modules

src/behavior-considered-undefined.md
Cc https://github.com/rust-lang/unsafe-code-guidelines/pull/190
=> Define sound and unsound

src/destructors.md
As part of rust-lang/rust#63230, it does not appear to be possible to create a partially initialized value.
cc @RalfJung @tmandry  Please correct me if I'm wrong, I am unfamiliar with this. I was planning to do an update today, but can't with breakage.
=> Update partially initialized values in drop documentation.

src/influences.md
At least I think it does? @steveklabnik can probably confirm.
=> our closure syntax comes from Ruby

stable-check/Cargo.toml, stable-check/src/main.rs
Building stable-check with Rust 2015 prints a warning saying that in Rust 2018 `dyn Error` instead of `Error` is required. This sets the edition of `stable-check` to 2018 and fixes the warning.
=> Fix warning in stable-check

src/abi.md, src/items/external-blocks.md, src/items/functions.md, src/types/function-pointer.md
The current reference of extern functions definitions is incorrect. It doesn't take into account that all "normal" Rust functions are `extern "Rust" fn`.
The section about external blocks specifies that only "non-Rust functions" (whatever that means) can be declared in external blocks. This is incorrect, since both an `extern "C"` Rust function, and a function with the `"Rust"` ABI, can be declared in external blocks.
=> Correct errors in the reference of extern functions definitions and declarations

src/SUMMARY.md, src/expressions.md, src/expressions/await-expr.md, src/expressions/block-expr.md, src/items/functions.md
I'm not sure what the best reviewing process is here.
cc @cramertj  @withoutboats @centril @joshtriplett @pnkfelix @scottmcm @pnkfelix @eddyb (I think that's the lang team, did I miss anybody?)
cc https://github.com/rust-lang-nursery/reference/issues/634 https://github.com/rust-lang/rust/issues/62566
=> async-await initial reference material

src/expressions/loop-expr.md
Somehow my mdbook transition script screwed up this link.
=> Fix loop expression link.

src/expressions/loop-expr.md, src/statements.md
Specify that patterns in
1. `if let` and `while let` are either refutable or irrefutable
2. `let` and `for` are always irrefutable
=>  Specify pattern types in `let` statements and `for` expressions

src/types/trait-object.md
AFAICT, this is no longer true.  Trying some of the examples in the linked issue, it appears the order is no longer significant.  It is also likely I am misunderstanding what this warning is trying to say, in which case if someone could clarify it I could update it.
=> Remove trait object warning.

src/attributes.md, src/conditional-compilation.md, src/const_eval.md, src/crates-and-source-files.md, src/dynamically-sized-types.md, src/expressions.md, src/expressions/block-expr.md, src/expressions/loop-expr.md, src/introduction.md, src/items/associated-items.md, src/items/functions.md, src/items/generics.md, src/items/unions.md, src/lifetime-elision.md, src/memory-allocation-and-lifetime.md, src/special-types-and-traits.md, src/subtyping.md, src/tokens.md, src/types.md
This is an update to correct for the places where the Oxford
comma is not used.
=> Fix #664: Review Oxford comma usage.

src/type-layout.md
The markdown parser has an issue (https://github.com/raphlinus/pulldown-cmark/issues/399) with a tag within a blockquote, so just make sure it is all on one line.
=> Fix abbr tag.

src/expressions/operator-expr.md
This documents the semantics proposed in https://github.com/rust-lang/rust/issues/62231
Closes #570
=> Specify behavior of int->float and f64->f32 casts

src/behavior-considered-undefined.md
Adjust to wording I agreed upon with @gnzlbg (somehow got lost from [the previous PR](https://github.com/rust-lang-nursery/reference/pull/659)).
Cc @Centril
=> unwind ABI wording tweak

src/keywords.md
Update for https://github.com/rust-lang/rust/pull/64875
=> Update async/await keywords to real keywords.

src/items/external-blocks.md, src/macros.md, src/procedural-macros.md
- macro invocations in `extern` blocks.
- fn-like proc macros as types
- make it more explicit where attribute proc-macros may be used
Closes #689
=> Add macros in extern blocks and new proc-macro support.

src/procedural-macros.md
Update for https://github.com/rust-lang/rust/pull/64035.
=> Update now that proc macros can expand to macro_rules.

src/attributes.md, src/expressions/closure-expr.md, src/items/associated-items.md, src/items/external-blocks.md, src/items/functions.md, src/items/traits.md, src/types/function-pointer.md
I guess this PR shouldn't be added before stabilization but for now it is publicly available for review
=> Add reference for attributes in function parameters

src/SUMMARY.md, src/attributes.md, src/attributes/type_system.md, src/glossary.md
This PR adds documentation for [RFC 2008](https://github.com/rust-lang/rfcs/pull/2008) (tracking issue rust-lang/rust#44109) to the reference.
=> Add `non_exhaustive` to reference.

src/items/functions.md
=> Document `const_constructor` feature

.github/workflows/main.yml
... ironic that in porting the reference away from rust-lang-nursery, we accidentally depending on mdbook still being in the nursery
=> github action doesn't use the nursery

src/special-types-and-traits.md
Fixes https://github.com/rust-lang/reference/issues/709
r? @Centril
=> expand Copy docs

src/items/modules.md
`no_implicit_prelude` also affects submodules of the module it's applied to.
rust-lang/rust#14969 says this is by design, so we should document it.
=> State that no_implicit_prelude also applies to nested modules

CONTRIBUTING.md, book.toml, src/introduction.md, src/types/inferred.md
Replace `rust-lang-nursery` with `rust-lang`
=> Update organization name

src/abi.md, src/attributes/codegen.md, src/attributes/type_system.md, src/conditional-compilation.md, src/crates-and-source-files.md, src/expressions/await-expr.md, src/expressions/field-expr.md, src/expressions/if-expr.md, src/expressions/loop-expr.md, src/expressions/operator-expr.md, src/items/enumerations.md, src/items/extern-crates.md, src/items/external-blocks.md, src/items/functions.md, src/items/generics.md, src/items/modules.md, src/items/unions.md, src/items/use-declarations.md, src/lifetime-elision.md, src/linkage.md, src/macros-by-example.md, src/paths.md, src/procedural-macros.md, src/runtime.md, src/tokens.md, src/trait-bounds.md, src/type-layout.md, src/types/closure.md
This is an attempt to reduce the amount of `ignore` code blocks. I find that they are dangerous, as they can allow invalid syntax, unintentionally broken code, accidentally start passing in the future, prevent running in the playground to view actual errors, etc.  Details:
- Comment on each `ignore` block why it is ignored.
- Remove `ignore` where it is easy to do so.
- Clean up some language tags.
- Fix a few broken examples.
=> Audit code blocks.

src/items/enumerations.md, src/types/never.md
- Add example of never type coercion.
- Mention equivalence to zero-variant enums.
I decided not to mention anything about type inference fallback, since it doesn't seem to really fit on the never type page, and there isn't any discussion about type inference elsewhere (#594).
=> Minor never type additions.

src/expressions/match-expr.md
Fixes #656
Fixes #719
r? @matthewjasper cc @ehuss
=> document `bind_by_move_pattern_guards`

src/items/enumerations.md, src/items/traits.md
Update for changes in https://github.com/rust-lang/rust/pull/66183.
I feel this is a little on the awkward side, particularly since it is such a niche concern. Also, I don't think the reference talks about the stages of compilation well enough to make these sorts of things clear. It might be a good idea for a new chapter in the future.
=> Update for visibility syntax changes.

src/types/never.md
Given that we are rolling back stabilization of the never type, this example needs a feature gate. The test was added only recently, by @ehuss -- I think that ordinarily we don't document unstable features, but given that this section of the book seems to be older, and that `!` can appear in some places, and that we hope to get `!` stabilized very soon, I opted not to remove it.
This needs to land semi-urgently so that https://github.com/rust-lang/rust/pull/67224 can land.
=> introduce feature gate into never-type test

src/abi.md
I originally interpreted this paragraph to mean `rustc` would also instruct the linker to keep the symbol. [This is not the case](https://github.com/rust-lang/rfcs/blob/master/text/2386-used.md#guide-level-explanation).
=> abi.md: clarify #[used] and linking

src/expressions/closure-expr.md
I was searching how to create anonymous functions but was unsure how in rust.  I searched the reference for "lambda" and nothing came up. I added a short little edit so anyone who searches lambda will be brought to the closure page.
=> Added clearification that closures are refered to lambdas

src/identifiers.md
`r#extern` is now accepted
cf. https://github.com/rust-lang/rust/pull/57572
=> Remove `extern` from exception list

src/macros-by-example.md
=> Fix typo in macros-by-example.md

src/items/external-blocks.md
This updates the reference to reflect the discussion from https://github.com/rust-lang/rust/pull/67630#issuecomment-569154116
=> Elaborate on how to use an extern static correctly

src/type-layout.md
The RFC and implementation have always required this.
=> repr(transparent): mention align=1 requirement

src/types/pointer.md
IIUC, this paragraph is still only talking about raw pointers, so I made
that explicit like in the two paragraphs above.
=> Small improvements to types/pointer.md

src/paths.md
Fixes https://github.com/rust-lang/reference/issues/746.
r? @ehuss
=> clarify note re. leading `::` in 2018

src/const_eval.md, src/items/enumerations.md, src/type-layout.md
"-less" is not a suffix that is generally hyphenated, and "field-less" looks odd compared to "fieldless". There's precedent for this choice in https://rust-lang.github.io/unsafe-code-guidelines/layout/enums.html.
=> Replace "Field-Less" with "Fieldless"

src/type-layout.md
Alternative to #559 incorporating some suggested changes to that PR.
@RalfJung I felt like your pseudocode approached actual code too much, and sorta requires understanding what's going on with `Layout` in order to follow, so I just took the route of making the padding calculation into an implicit function per other suggestions.
=> Fix incorrect pseudocode for #[repr(C)] struct alignment

src/patterns.md
Obviously, a tuple struct pattern allows leaving out the `TupleStructItems` [[playground example]](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2d1633b13083df14a945ac00c0b59cdb).
=> Fix grammar for tuple struct patterns.

src/expressions/block-expr.md, src/expressions/match-expr.md, src/statements.md
Semicolon or comma in expression statements or match arms, respectively, are optional, but part of the statement / match arm.
Also remove a note about proc-macros from the page about BlockExpression.
Closes #773 and closes #774.
=> Fix expression and statement grammar.

src/types/inferred.md
The `rustc-guide` is being renamed to the `rustc-dev-guide`. The discussion is in rust-lang/rustc-guide#470.
This PR revises `rustc-guide` to `rustc-dev-guide` in a Markdown file.
Transition tracker: rust-lang/rustc-guide#602
=> Update rustc-guide to rustc-dev-guide

src/items/use-declarations.md
Section on use-visibility fixed to compile under Rust 2018, since they are not absolute paths by default anymore.
=> Fix and clarify section on re-export

src/type-layout.md
```c
#include<stdio.h>
struct A {
};
int main() {
struct A a;
printf("%ld\n", sizeof(a));
}
```
```bash
$ gcc tmp.c
$ ./a.out
0
$ g++ tmp.c
$ ./a.out
1
```
=> Size fo empty structs in C is zero byte.

CONTRIBUTING.md, STYLE.md
cc #599
This is intended to be a simple start for things that are hopefully not too controversial.
=> Add a basic style guide.

src/attributes.md, src/attributes/derive.md
It's not clear if this *should* be documented. Alternatively, it could be deprecated if usage in stable is really not desired. Not sure who can make this call.
Implemented in: https://github.com/rust-lang/rust/pull/12929
CC #532
=> Document the `automatically_derived` attribute.

src/expressions/loop-expr.md
Also fix italics to be consistent with other pages.
See #771. I also copied and adapted the corresponding paragraph from the `if let` page.
_Edit: Instead of copying the paragraph from `if let` mentioning the unstable `if-let chains` feature, now the copy as well as the original paragraph are removed._
=> Add information about || and && to grammar describing `while let`.

src/visibility-and-privacy.md
I had a bit of trouble understanding the pub(restricted) syntax. Hopefully i got it now. The two things i had problems with are:
- 'pub(self)' and no 'pub' seem to be exactly the same, but the fact that it is not stated in the docs suggests them to be different.
- 'pub(...)' never increases the visibility over 'pub', it just restricts it more. You can write 'pub(crate)' in a module that is not visible within the scope of the crate. Doing this isn't really useful, but the fact that it's possible may be a bit confusing.
I suggest to add something to the documentation to clarify this a bit.
=> Clarify pub(restricted) a bit

src/items/use-declarations.md
The current documentation is woefully out of date and incomplete.  I've been trying off and on to study the resolver to begin #568, which will be required to finish this, but I probably won't be able to finish for a long while.
=> Undocument `use` paths.

src/type-layout.md
Stabilized in https://github.com/rust-lang/rust/pull/68122.
r? @ehuss 
cc @rkruppe
=> `enum`s can now be `#[repr(transparent)]`

src/expressions.md
This became possible with https://github.com/rust-lang/rust/pull/69201
=> Attributes are now allowed on `if` and `if let`

src/items/unions.md
I spent a minute trying to parse this sentence until I realized it was missing a comma.
=> Added missing comma to Unions reference

src/destructors.md, src/expressions.md, src/expressions/loop-expr.md, src/expressions/operator-expr.md, src/introduction.md, src/types/pointer.md, src/variables.md
=> Document drop scopes

src/patterns.md
A trailing comma after '..' in a tuple or tuple struct pattern without another pattern between them is valid syntax:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=dc7ce799af060019bb97b87cb9fb1294
=> Fix grammer for tuple patterns and tuple struct patterns

src/visibility-and-privacy.md
"Parent" means the first level above, "ancestors" means all the levels above.
=> Replace incorrect term "parent modules" with "ancestor modules".

src/behavior-considered-undefined.md
Ever [since Rust 1.0](https://doc.rust-lang.org/1.0.0/reference.html#behavior-considered-undefined), the reference said that a non-UTF-8 `str` causes immediate UB. In terms of [today's terminology](https://www.ralfj.de/blog/2018/08/22/two-kinds-of-invariants.html), that means that `str` has a validity invariant of being valid UTF-8.
However, that seems unnecessary: the compiler does not actually exploit this, nor is there any clear way it could exploit this. Making UTF-8 a library-level *safety invariant* is more than enough for everything `str` does. Most likely, it was made a validity invariant because we had not yet properly teased apart those two concepts when the document was initially written. 
This is also the conclusion that the UCG WG arrived at in …
=> remove language-level UB for non-UTF-8 str

src/items/functions.md
=> Fix stray plus signs.

src/expressions/operator-expr.md
This updates the reference per PR rust-lang/rust#71269.
=> Account for removal of UB in float-to-int casts

src/conditional-compilation.md
The example for cfg_attr needs a valid predicate. `linux` on it's own doesn't work. I think this likely slipped through because `windows` on it's own looks valid because it's a target_family which set their value like `unix` and `windows`. Not sure.
=> cfg_attr needs a valid predicate

src/types/textual.md
Cc @ehuss (https://github.com/rust-lang/reference/pull/792)
=> work on char/str descriptions

src/attributes/diagnostics.md
This was fixed in https://github.com/rust-lang/rust/pull/62042.
Closes #803
=> Update that macros can be deprecated.

src/paths.md, src/tokens.md
=> Fixes minor errors

src/expressions/enum-variant-expr.md, src/expressions/struct-expr.md, src/expressions/tuple-expr.md, src/patterns.md, src/tokens.md
The tuple index is not a distinct token lexically, so don't treat it as such.
Also, add a note about the future-compatibility issue with suffixes.
Closes #735
=> Update tuple index token.

src/procedural-macros.md
Stabilized in https://github.com/rust-lang/rust/pull/68717.
This doesn't update anything about macro hygiene, which seems like a whole project in itself.
=> Update fn-like proc-macro invocation restrictions.

src/expressions/array-expr.md
Noticed a small error while reading through the reference here
=> Fix sentence mistake in array-expr.md

README.md, src/linkage.md
As they don't have anything specific to bash
=> change bash to sh as shell code blocks language indentifier

src/expressions/call-expr.md
Adds a cross-link from Disambiguating Function Calls to the relevant qualified paths section. Also some links for clarity on some std functions.
Closes #597
=> Add some links to Disambiguating Function Calls.

src/whitespace.md
Just a minor thing. Not sure if it is really helpful, since the actual property is defined in the bowels of the unicode character database.
=> Add a link to the definition of Pattern_White_Space.

src/items/extern-crates.md
`proc_macro` no longer needs to be declared when used with Cargo as of https://github.com/rust-lang/cargo/pull/7700.
Closes #789
=> Fix note about using proc_macro with Cargo.

src/expressions/loop-expr.md
Since the original code is `'label: for PATTERN in iter_expr {`, the variable name should be `PATTERN` too.
=> Fix an invalid variable name in the loop example

src/items/type-aliases.md
The current version of the reference for `type-aliases` currently claims that you cannot qualify constructors for enums through type aliases, but this is no longer true. AFAIK the only type of constructor that type aliases can't be used for are `tuple-structs`. tuple-enums, non-tuple-enums, and non-tuple-structs all construct just fine through type aliases.
=> fix out of date info on type aliases

src/conditional-compilation.md
=> Mention `feature="foo"` is a Cargo convention.

src/expressions.md
Being new to Rust and lacking an in-depth understanding, I still think this is probably a cut-n-paste error and should be fixed.
=> Fix name of trait for array indexing.

src/types/trait-object.md
`UnwindSafe` was typo'd as `Unwindsafe`.
=> Fix mis-capitalization of type name.

src/crates-and-source-files.md
Parsing of shebang was changed in https://github.com/rust-lang/rust/pull/71487.
It was a little too awkward to define the syntax in the limited grammar syntax, so I just wrote the rules in English.
=> Document shebang restriction.

src/special-types-and-traits.md
=> Added Unpin to list of Auto Traits

src/patterns.md
Add word "underscore" for better search accessibility.
`_` is a short, widely-used symbol and I didn't even try to search for it.
I think this simple change can prevent someone (would have prevented me) from being confused & asking on Reddit :)
=> patterns.md - add word "underscore" to _ paragraph

src/tokens.md
Some usages that I missed previously.
=> Update token usage table.

README.md
The `mdbook build` default output directory is `book`, not `docs`.
=> Fix documented build output path.

src/attributes/codegen.md
=> mention that `#[track_caller]` on `fn main` is forbidden

src/subtyping.md, src/type-layout.md
Bare `Trait` is deprecated, so these examples should use `dyn Trait`.
=> Update to `dyn Trait` syntax in a couple places

src/conditional-compilation.md, src/types/numeric.md
=> Document min pointer width.

src/expressions/operator-expr.md
There casting rules have been already compilable in stable Rust: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=837e70f00bbcbf16f91cfc1c8016af8e
Zulip discussion: https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/Reference.20missing.20casting.20rules.20for.20function.20items
=> Add casting rules from function items to other types

src/const_eval.md, src/items/constant-items.md, src/items/static-items.md, src/types/array.md
- Clarify that array length is a "constant expression". Closes #582.
- Remove restriction that statics must use other statics by reference. This was removed in https://github.com/rust-lang/rust/pull/51110 (1.29 I believe).
- Clarify that paths to statics are allowed only within static initializers.
- Add a clarification of usage of constants from external crates (closes #22 I believe).
- Mention that generic parameters cannot be used in a const context (https://github.com/rust-lang/rust/issues/43408)
- Some other minor tweaks.
=> Some constant/static updates.

src/expressions/match-expr.md
This PR adds the assignment of x back into the match example. Without it, the example doesn't seem to make sense.
=> Added variable back into example.

src/type-coercions.md
I've updated pull request #342 by @Havvy by fixing the merge conflicts, and additionally adding a fix to close #734 (Incorrect examples of type coercion).
=> Improve Type-Coersion Documentation

src/patterns.md
This updates the patterns chapter, primarily adding "rest patterns", stabilized in 1.42. See stabilization report: https://github.com/rust-lang/rust/pull/67712#issue-357908384
This also includes a few extra updates that I noticed along the way.
I'm not 100% confident on the refutability changes, since I've never bothered to understand the [usefulness code](https://github.com/rust-lang/rust/blob/master/src/librustc_mir_build/thir/pattern/_match.rs), so it is just based on my own understanding.
Closes #739
=> Update patterns chapter, add rest patterns.

src/behavior-considered-undefined.md
This should hopefully help avoid confusion like [this one](https://internals.rust-lang.org/t/why-even-unused-data-needs-to-be-valid/12734/23?u=ralfjung).
=> clarify when reading uninititalized memory is allowed

src/type-layout.md
Document the changes introduced in https://github.com/rust-lang/rfcs/blob/master/text/2195-really-tagged-unions.md.
Fixes #244 (I believe), fixes #786.
This is your RFC so I'll tag you @Gankra.
This is a restart from #246, applying the comments that were given at the time.
Disclaimer: I have never personally used this feature and only tested using the playground so I may be missing things, I'm sorry if that's the case.
=> Document the enum changes in RFC 2195

src/linkage.md
Now Windows MinGW uses `.a` extension for staticlib.
c.f. https://github.com/rust-lang/rust/pull/70937
=> Update the description of staticlib

src/type-coercions.md
As requested in <https://github.com/rust-lang/rust/pull/71599>. Also references the <https://github.com/rust-lang/rust/issues/48109#issuecomment-365045690>
=> Add description for LUB Coercion

src/attributes/codegen.md
According to LLVM source code: https://github.com/llvm/llvm-project/blob/544a6aa2674e3875e4014eafb101a982f9296439/llvm/lib/Target/X86/X86.td#L66-L82
Fixes https://github.com/rust-lang/reference/issues/891
=> Specify that SSE4.1 includes SSSE3 instead of SSE3

src/patterns.md
Documenting `move_ref_pattern` for stabilization. (see rust-lang/rust#76049)
This is waiting for the stabilizing PR to be merged
=> Add `move_ref_pattern` docs

src/items/unions.md, src/types/union.md
Cc https://github.com/rust-lang/rust/pull/77547
r? @ehuss
=> mention how unions interact with dropping

src/items/external-blocks.md, src/items/modules.md
New syntax added in https://github.com/rust-lang/rust/pull/75857/.
=> Add `unsafe` for `mod` and `extern`.

.github/workflows/main.yml
The old method of echoing commands is being deprecated, see https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/.
=> Update deprecated GitHub Actions commands.

src/expressions/tuple-expr.md, src/patterns.md, src/types/tuple.md
I'm not sure "initialized" is the correct word, but I feel like our
verbiage around place and value expressions need to be cleaned up
anyways. I originally went with "moved", but that's not really correct.
I think I want to call it a "value operand", but I need to discuss with
others on that first. In any case, it's a lot more correct than what
was there before.
In one example, I renamed `unit_x` to `point` because while it's technically a mathematical unit, it clashes with the unit tuple.
I also kept `element` instead of renaming to `field`.
=> Referencify tuples

src/introduction.md
We're no longer using Discord as we're not a part of the docs team
anymore since there is no docs team anymore.
=> Update where our chat is.

src/items/functions.md
Using `test` causes a deny-by-default lint to trigger. See
https://github.com/rust-lang/rust/pull/79003 for more information.
=> Use `doc`, not `test` for fn item inner attr example

.gitignore, src/introduction.md
Also add stable-check/ to the .gitignore
=> Describe relationship between reference and optimizers

src/items/unions.md, src/types/union.md
Update for the change in https://github.com/rust-lang/rust/pull/78068.
=> Update unions for safe ManuallyDrop assignment.

src/expressions/array-expr.md
Documentation for https://github.com/rust-lang/rust/pull/79270.
I did not include any details about drop behavior with `[a; 0]`, as it seems like https://github.com/rust-lang/rust/issues/74836 is unresolved, though I can add that if desired.  (I'm not sure if that would go in the array-expr chapter, or the destructor chapter.)
=> Document array expression with a const.

src/linkage.md
Hi! I've tried to verify that this works but using `mdbook build` creates a broken link locally (in the output, `book` is the directory containing the reference, not the Book). This format, however, matches the link to the book from [`runtime.md`](https://doc.rust-lang.org/stable/reference/runtime.html#standard-behavior), which does work.
=> linkage.md: update link to FFI section of the Book.

src/SUMMARY.md, src/const_eval.md, src/items/generics.md, src/paths.md
blocked on the stabilization of `min_const_generics`.
=> document const generics

src/types/tuple.md
Before:
After:
Caught by cargo-deadlinks in https://github.com/deadlinks/cargo-deadlinks/issues/133#issuecomment-748399781.
=> Fix formatting in the tuple section

src/items/associated-items.md, src/items/enumerations.md, src/items/external-blocks.md, src/items/functions.md, src/items/generics.md, src/items/implementations.md, src/items/structs.md, src/items/traits.md, src/items/type-aliases.md, src/items/unions.md, src/paths.md
Generic param order restriction was changed in https://github.com/rust-lang/rust/pull/58191.
Generic argument order restriction was changed in https://github.com/rust-lang/rust/pull/70261.
`for` lifetime argument restriction was changed in https://github.com/rust-lang/rust/pull/48326.
Generic parameter parsing: https://github.com/rust-lang/rust/blob/206ee1eea3467fd1d7f1efdbeafe27880897bb2c/compiler/rustc_parse/src/parser/generics.rs#L83-L153
Generic argument parsing: https://github.com/rust-lang/rust/blob/17eec1433c69972844dd228b5fe801f218e118c3/compiler/rustc_parse/src/parser/path.rs#L395-L413
`for` argument parsing: https://github.com/rust-lang/rust/blob/206ee1eea3467fd1d7f1efdbeafe27880897bb2c/compiler/rustc_parse/src/parser/ty.rs#L724-L736
Fixes #785
=> Update grammar for order of parameters/arguments.

src/behavior-not-considered-unsafe.md
In https://github.com/rust-lang/rust/issues/80657 and https://github.com/rust-lang/rust/pull/80681 it is discussed how to clarify/define what a "logic error" is and what are their consequences. The reference should mention them as well.
We could use other term instead of "unspecified", e.g. "unpredictable"; in case we want to emphasize that the results may not the same between runs, builds, kinds of build, etc. For instance, from the description of integer overflow, it looks like the implementation needs to choose some reasonable behavior (e.g. a panic or wrap around), even if not documented (therefore, "unspecified", in terms of the C and C++ standards). However, logic errors seem to require more freedom: the implementation may not even be able (or want) to predict what may happen, so it …
=> Add "Logic errors" as behavior not considered unsafe

src/types/enum.md, src/types/struct.md
The script I ran in #641 was a little overzealous, and corrupted a few footnotes.
=> Fix footnotes.

src/items/generics.md, src/items/implementations.md
This is an extension of #901 with some more details about const generics.
This is not intended to be exhaustive of everything regarding const generics, just to add a little bit more information that I'm aware of.
=> Add more details about const generics.

src/tokens.md
This seems to me to me the only actionable thing to the confusion in pr #922.
=> Add a float examle without a `.`.

src/items/associated-items.md, src/items/constant-items.md, src/items/external-blocks.md, src/items/functions.md, src/items/implementations.md, src/items/static-items.md, src/items/traits.md, src/items/type-aliases.md, src/types/function-pointer.md
Updates the grammar for function and associated item unification/simplification. Over a series of PRs, various parts of the grammar were unified so that some the same grammar is reused in various places, with restrictions and validation applied after parsing.
Some of the PRs:
* https://github.com/rust-lang/rust/pull/67131: Merge `TraitItem` & `ImplItem` into `AssocItem`
* https://github.com/rust-lang/rust/pull/68728: merge `fn` syntax + cleanup item parsing
* https://github.com/rust-lang/rust/pull/68764: syntactically allow `self` in all `fn` contexts
* https://github.com/rust-lang/rust/pull/68788: towards unified `fn` grammar
* https://github.com/rust-lang/rust/pull/69023: unify function front matter parsing
* https://github.com/rust-lang/rust/pull/69194: fuse associated and extern items …
=> Update grammar for parser unification.

src/expressions/operator-expr.md
This is the final part of #248, split off from #888 since I have questions on this part and don't want to block #888 on it.
Specifically, is this desugaring correct? I asked on Zulip a few weeks ago, but got no definitive answer.
Also, is it possible to have a relative link to a test file?
=> Compound operator expressions

src/expressions.md, src/expressions/operator-expr.md
Thank eddyb and Steve Klabnik for complaining on Twitter for this PR.
Closes #248
The order is now documented. I considered using an example over expression evaluation using println!, but the twitter thread is explicitly using iterators and this is probably the most common reason to care about evaluation order in tuple expressions anyways.
I also cleaned up the page to bring it into style compliance. I did both at the same time, so there's only one noisy commit. Sorry to the reviewer.
=> Document execution order

src/expressions/operator-expr.md
Best seen with a word or rich diff.
=> Fix plural and delete spurious words in comparison ops

src/SUMMARY.md, src/attributes.md, src/crates-and-source-files.md, src/glossary.md, src/items/extern-crates.md, src/items/modules.md, src/items/use-declarations.md, src/keywords.md, src/macros-by-example.md, src/names.md, src/names/name-resolution.md, src/names/namespaces.md, src/names/preludes.md, src/names/scopes.md, src/paths.md
This is a very small start to making progress on documenting name resolution (#568). This PR focuses on:
- Create the "names" chapter, with an introduction, and list of all things that introduce names.
- Document namespaces.
- Consolidate and extend preludes.
- Move the "Paths" chapter underneath the names chapter.
- Move the "Visibility" chapter underneath the names chapter.
Closes #924.
=> Start documenting name resolution.

.gitignore, README.md
In this PR, I have refactored the build steps of the project in the _README.md_ file so they are better readable, easier to follow, and more detailed.
=> Refactored build steps for better readability

README.md
In context to issue #954, setting Rust nightly is a requirement to be able to successfully run the tests, which is nowhere mentioned in the README.md file. This PR addresses that pre-req to the README.md file.
=> Added setting nightly as a requirement for running tests

src/SUMMARY.md, src/memory-ownership.md
It's a holdover from pre-Rust 1.0 when the reference was the main
document to understand anything about the language. Its contents are
completely meaningless and to avoid having hopeful people step into this
useless page and have their hopes smashed, we are removing it.
=> Remove "Memory Ownership" chapter

src/introduction.md
Fixes #947 
I'm not super satisfied with what I've written here, but I think it's an improvement over not saying anything at all. I've also included a how to find other versions thing in there since it felt appropriate.
=> Define rust

src/expressions/operator-expr.md
Typo originally reported in the compiler issue tracker:
https://github.com/rust-lang/rust/issues/81686#issuecomment-772820785
It doesn't make sense to cast a pointer to a float, and it's currently
rejected by the compiler:
error[E0606]: casting `*const T` as `f32` is invalid
--> test.rs:2:5
|
2 |     a as f32
|     ^^^^^^^^
error: aborting due to previous error
I think what's meant here is "integer type" rather than "numeric type".
=> Fix typo in type cast expression table

src/behavior-considered-undefined.md, src/expressions/if-expr.md, src/expressions/loop-expr.md, src/expressions/operator-expr.md, src/items/unions.md, src/types/boolean.md
I never knew there was so much to say about booleans.
=> Referencify bool type

src/expressions/array-expr.md, src/expressions/await-expr.md, src/expressions/block-expr.md, src/expressions/call-expr.md, src/expressions/closure-expr.md, src/expressions/field-expr.md, src/expressions/grouped-expr.md, src/expressions/if-expr.md, src/expressions/literal-expr.md, src/expressions/loop-expr.md, src/expressions/match-expr.md, src/expressions/method-call-expr.md, src/expressions/operator-expr.md, src/expressions/path-expr.md, src/expressions/range-expr.md, src/expressions/return-expr.md, src/expressions/struct-expr.md, src/expressions/tuple-expr.md
I'm going to be doing editorial cleanup on every page, so instead of hiding everything in that PR, I'm making this one separate.
=> One sentence is one line src/expressions/*

src/glossary.md
=> Define turbofish in the glossary

src/subtyping.md
While discussing variance on a Rust help channel, I noticed that the subtyping chapter does not specifically mention the special case where a type parameter is used both in the input and output of a function, which, as far as I know, would make it be treated as invariant because its the intersection of both contravariance and covariance.
In case I'm not totally wrong with this, I propose adding that case to the table to make it a bit more clear.
=> Add an extra fn() entry to the variance table in the subtyping chapter

src/paths.md
Part of https://github.com/rust-lang/rust/issues/82876
=> Clarify that ::foo paths are not necessarily based off of the "crate root"

src/expressions/operator-expr.md
My attempt to address #979. Does this help?
This may cause a merge conflict with #961 .
=> Explicitly note any cast not defined in the documentation is illegal.

src/attributes/limits.md
This updates the auto-deref recursion_limit example for https://github.com/rust-lang/rust/pull/82834. Previously this actually hit the recursion limit while evaluating the Freeze bound, not during auto-deref. The current example only needs one level of deref to reach the argument type. This adds one more level of nesting, so that two derefs are actually needed, and recursion_limit is hit during auto-deref and not sometime later:
```
error[E0055]: reached the recursion limit while auto-dereferencing `&{integer}`
--> test14.rs:5:19
|
5 |     (|_: &u8| {})(&&&1);
|                   ^^^^ deref recursion limit reached
|
= help: consider adding a `#![recursion_limit="2"]` attribute to your crate (`test14`)
```
Previously:
```
error[E0275]: overflow evaluating the requirement `(): …
```
=> Update auto-deref recursion_limit example

src/expressions/operator-expr.md
- Add reference-to-pointer casts
- Update array-to-pointer casts for [rust#81479][1]
[1]: https://github.com/rust-lang/rust/pull/81479
=> Update type casts section

src/expressions.md, src/expressions/array-expr.md, src/expressions/await-expr.md, src/expressions/block-expr.md, src/expressions/call-expr.md, src/expressions/closure-expr.md, src/expressions/field-expr.md, src/expressions/grouped-expr.md
* Use "the syntax of" uniformly.
* Use asterisks for all defined terms.
* Define more terms, espcially in the syntax section.
* * Reword things so that definitions are generally first.
* * I did not necessarily go with the best wording; the idea is to
improve, not perfect. I still need to dedicate time to each
expressions individually.
* Remove usage of "the compiler" and "Rust".
* * This also involved rewording.
* * How to deal with closure types and closure expressions is gonna be
an interesting question to solve. I avoided solving it here.
* Remove non-normative information or put them in a `Note`.
* A few added section headers
* Move links to the bottom
Note that I've left quite a few nonsensical statements alone, such as
any that use "denote". They'll be treated separately.
About …
=> Editorial cleanup on expressions (part 1)

src/const_eval.md
Const generic arguments are a "const context", so add them to the list.
Also, a const context has limited support for using const parameters.
=> Add const generic args to const contexts.

src/items/traits.md
When trying to figure out how `async_trait` object safety worked and thinking about `Stream::next`'s object safety, I found it very hard to understand 
This clarifies that object-safety can still be possible even if a method is striked from the vtable, and that `self` and `where `Self: Sized` are the ONLY ways to do that.
This was only really explained clearly in the examples below, so this includes this clarification in the object safety rules in the beginning of the section
---
Separately, NonDispatchable seems like you are out of luck, but this pattern: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5529e6424895cccda19d4dd81f389b69, where we impl the trait for &T where T: Trait + ?Sized is actually quite common in the std (albeit with `self` parameter's so you …
=> Clarify object safety rules for methods striked from the vtable

src/expressions/tuple-expr.md, src/types/tuple.md
The first commit is just switching the tuple type page to one line is one sentence. Check the second commit for actual changes.
I'm hoping this is overall more readable and more explicit about what each thing means.
=> Tuple Passover #2

src/types/pointer.md
The second commit has the actual change. Just linking to the macros so that people can find them easier.
There are also a few switches from commas to periods in the first commit where they were actually different sentences.
=> Link to ptr::addr_of on raw pointer docs

src/attributes/diagnostics.md
`rustdoc` was added in https://github.com/rust-lang/rust/pull/80527.  Also, moved this to a callout since I consider it implementation-specific.
=> Add rustdoc to tool lints.

src/attributes/diagnostics.md
This adds some clarification about some details of lint level behavior. 
This should cover https://github.com/rust-lang/rust/pull/77534 in a roundabout fashion (by specifying the order that the attributes are processed).
This does not include a special callout for https://github.com/rust-lang/rust/issues/81670. I figure that is just a small bug in rustc, and this falls out of my personal threshold for being mentioned. This documents what was intended (that groups conceptually expand to the list of lints within them, and that the order of lints usually matters).
Some of this documentation could potentially be moved to the rustc book if it is decided that it is too implementation-specific. In particular, this describes the "warnings" group due to its unusual behavior. To me, this is a gray …
=> Update lint level documentation.

src/behavior-considered-undefined.md
Following [discussions on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/136281-t-lang.2Fwg-unsafe-code-guidelines/topic/Deferencing.20Bad.20Value.20UB.20Reference.20Description)
=> clarify UB for raw ptr deref

src/identifiers.md
`non-ascii-idents` feature is now in fcp. Moving its unstable book contents to reference.
=> Move non-ascii-idents content from unstable book to reference.

src/linkage.md
It adds a little bit more information to the `bin` crate type and standardizes the style below where the operating systems are listed.
=> Improve clarity and style consistency of crate type list

src/items/traits.md
line 46: Trait functions are **are** not allowed to be [`async`] or [`const`].
now: Trait functions are not allowed to be [`async`] or [`const`].
=> fixed a typo in traits.md

src/expressions/closure-expr.md, src/expressions/if-expr.md, src/expressions/loop-expr.md, src/expressions/match-expr.md, src/items/functions.md, src/macros-by-example.md, src/patterns.md, src/statements.md
cc https://github.com/rust-lang/rust/pull/79278 https://github.com/rust-lang/rust/issues/54883 @joshtriplett 
@petrochenkov This also allows the leading vert change according to the T-lang FCP in https://github.com/rust-lang/rust/issues/81415
=> Document or-patterns

src/items/traits.md
Change misspellings of `reciever` to `receiver`
=> Fix typo in `Traits`

src/conditional-compilation.md
This generalizes the `target_family` to allow it being specified more
than once and apply to other properties than just the operating system
family.
Of particular interest is an ability to match architectures that are a
part of a family of architecutes (e.g. various versions of ARM, WASM or
other targets)
=> Adjust the definition of `target_family`

src/expressions/operator-expr.md
The existing text implies but doesn't explicitly say that
compound assignment produces the unit value. A reader could also
infer it from the signatures of the compound assignment trait
functions, but it seems better to be explicit.
=> Explicitly state result of compound assignment

src/attributes.md
Closes https://github.com/rust-lang/reference/issues/1028.
r? @petrochenkov cc @nikomatsakis
=> Document extended key-value attributes

src/types/impl-trait.md
Much of this comes from the edition-guide. Some information comes from the RFCs about the `impl Trait` feature. (rust-lang/rfcs#1522, rust-lang/rfcs#1951, and rust-lang/rfcs#2250)
Some finer points from the RFCs might need to be added, but maybe a new issue should be opened to enumerate and track those? I guess the biggest one would be checking that the syntax changes of rust-lang/rfcs#2250 are adequately documented in the reference. Lifetime defaults, especially for `impl Trait` in return position, should probably also be checked.
CC #276.
=> Add more content to impl-trait.md

src/items/implementations.md
The example in Trait Implementations was missing a parameter name in a
trait method declaration, which is no longer allowed in the
2018 edition.
=> missing parameter name in Trait Implementations

src/macros-by-example.md
This reverts commit 629e7df5dc6fda16af98bc40cd139de0e0fa73a2.
https://github.com/rust-lang/rust/pull/83386 merged sooner than I expected.
=> Revert "Temporarily remove pat_param."

src/items/generics.md, src/trait-bounds.md, src/types/function-pointer.md
_ForLifetimes_ are used in multiple places, so I don't think it makes sense to define them as part of _WhereClause_. Also, I often got confused hitting the "Higher-ranked trait bounds" section and not seeing the grammar there.
=> Rearrange HRTB grammar.

src/attributes/limits.md
The existing example for the `type_length_limit` attribute wasn't failing as expected.  Somewhere between 2020-09-18 and 2020-09-19 the old example stopped failing (maybe https://github.com/rust-lang/rust/pull/72412 or https://github.com/rust-lang/rust/pull/76575, I can't tell).
I adjusted the example to require some recursion which now triggers the error. This is more similar to the [existing test](https://github.com/rust-lang/rust/blob/fe72845f7bb6a77b9e671e6a4f32fe714962cec4/src/test/ui/type_length_limit.rs).
Additionally, since https://github.com/rust-lang/rust/pull/68664, `ignore` can be removed and it should check the example now.
=> Fix type_length_limit example.

src/glossary.md
=> Add crate and module to glossary.

src/statements.md
A variable is not visible in its entire scope; only where it is not shadowed by a different variable declaration with the same name.
=> Make statement about variable visibility more precise

src/attributes/codegen.md
Also document the `simd128` feature stabilized in rust-lang/rust#86204
=> Add notes on `#[target_feature]` for wasm

src/expressions/operator-expr.md
This is a counterpart to https://github.com/rust-lang/nomicon/pull/277.
=> Add a note why the same size int casting is a no-op

src/expressions/operator-expr.md
See https://github.com/rust-lang/rust/issues/86099#issuecomment-862857244 for some more context. These operations always panic, even when overflow checks are disabled.
=> Mention that MAX / -1 and MAX % -1 always panic

src/macros.md
The description of "procedural macros" was never updated when function-like procedural macros were stabilized.
Also, I felt like the word "executes" could be confusing, since it doesn't actually execute the code *in* the macro, so I tried a different word that is closer to the terminology typically used (expansion).
=> Minor update to macros.

book.toml, src/expressions/block-expr.md, src/introduction.md, src/items/functions.md, src/items/traits.md, src/items/type-aliases.md, src/items/use-declarations.md, src/paths.md, src/trait-bounds.md, src/visibility-and-privacy.md
I would like to move the reference towards describing the latest edition first and foremost.  This is a small step to switch all the examples to default 2018 unless otherwise noted.
Closes #1039
cc #281
=> Default all examples to 2018 edition.

src/names/namespaces.md
Sub-namespaces were introduced in https://github.com/rust-lang/rust/pull/54069.
=> Document sub-namespaces.

src/expressions/if-expr.md, src/expressions/loop-expr.md, src/expressions/match-expr.md
Adding an explicit mention of the scrutinee in the grammar snippet makes the usage of the term in the description clearer, at @zancas's suggestion.
=> Make explicit reference to scrutinee expression in grammar snippet

src/type-layout.md
Currently it states that the nth element has an offset of n*(size of type). I think this is assuming that people are starting at 0, but that's not really what `nth` implies. The first element has an offset of 0, but currently it implies that `n=1`, giving it a non-zero offset.
This might want a larger rewording, but I added the zero-case explicitly to try and be clearer.
=> Be more precise about array offset in type layouts

src/items/type-aliases.md
Fixes #1032.
I did not know how to add the information that this documented syntax is not always correct. (the `*` in the original issue)
=> Missing TypeParamBounds in TypeAlias

src/items/static-items.md
Inspired by [this urlo question](https://users.rust-lang.org/t/how-to-make-sure-types-that-implement-a-trait-do-not-share-implemented-functions/45123/2). I don't know if this is correct, someone from the lang team should probably review.
=> Clarify defining static items in a generic scope

src/expressions/operator-expr.md
A follow-up to https://github.com/rust-lang/nomicon/pull/256.
=> Mention (negative) infinity values on float-to-int casting

src/macro-ambiguity.md
Checked https://raw.githubusercontent.com/rust-lang/rfcs/master/text/0550-macro-future-proofing.md, there is no `\`s in that file.
=> fix typo in macro-ambiguity.md

src/destructors.md
In "Scopes of function parameters" under "Destructors", the first
comment in the example that demonstrates function parameter
drop order contradicted both the text and the program behavior.
=> fix comment in function parameter drop scope example

src/expressions.md
Fix minor grammar errors in Expressions, mostly adjusting
punctuation, but also fixing missing or incorrect words.
=> fix grammar in Expressions

src/types/closure.md
This improves the wording a bit, which came up in https://users.rust-lang.org/t/why-compiler-prefer-failed-than-choosing-move/62071
=> Clarify closure capture modes slightly

src/expressions/array-expr.md, src/expressions/grouped-expr.md, src/expressions/struct-expr.md, src/expressions/tuple-expr.md
Inner attributes were removed in https://github.com/rust-lang/rust/pull/83312, with https://github.com/rust-lang/rust/pull/85193 re-adding support in match expressions.
Closes #1021
=> Remove inner attributes from non-block expressions.

src/items/generics.md, src/trait-bounds.md
Move text about the timing of checking of bounds on generics
from the "Where clauses" subsection to "Trait and lifetime
bounds", where it makes more sense. Split parts of the example
accordingly. Correct an error about when `Clone`, `Copy`, and
`Sized` trait bounds are checked.
Fixes #1024.
I'm not sure if the previous text about checking trait bounds on generics at the definition instead of at the use site was ever correct, but it doesn't seem correct now on stable.
=> move text about checking of bounds on generics

src/dynamically-sized-types.md, src/items/associated-items.md, src/special-types-and-traits.md, src/trait-bounds.md
Mention that there is an implicit `Sized` bound on associated types
as well as on type parameters. Make it more clear that `?Sized`
relaxes the implicit `Sized` bound. Also fix some grammar issues
where omitted words caused confusion.
Fixes #1023. Credit to @mcclure for working on this earlier in #992.
Closes #987, closes #992
=> mention implicit `Sized` bound in more places

src/items/generics.md, src/trait-bounds.md
Clarify that "outlives" really means "lives at least as long as".
Also fix some more minor punctuation and wording issues.
Based on #1060.
=> fix wording/punctuation in "Lifetime bounds"

src/types/tuple.md
This should be the other form of its.
I couldn't unsee it after I noticed it. ❤️
=> Remove incorrect apostrophe

src/identifiers.md
This expands on #999 with more details about the definition of an identifier.
=> Expand on Unicode identifiers.

src/expressions/array-expr.md
I'm pretty sure 'legnth' was supposed to be 'length'. Also added a gerund to let the sentence appear a little more sound/formal.
=> array-expr.md: fix typo; 'polish' sentence

src/patterns.md
This adds a example of binding a varible after an `@`. `bindings_after_at` is currently unstable, but if [85305](https://github.com/rust-lang/rust/pull/85305) is merged, it may merit an example (so dont merge this untill then :sweat_smile:). I think one could argue the feature is obscure enough that the example may be more noise than useful. I'll leave that call up to those with more expirence than myself.
=> example for bindings after at

src/type-coercions.md
Fixes https://github.com/rust-lang/nomicon/issues/237
This is mentioned in [RFC 401](https://github.com/rust-lang/rfcs/blob/master/text/0401-coercions.md#function-type-polymorphism) but it seems the reference doesn't mention it currently.
=> Mention "function item type to `fn pointer`" coercion

src/expressions.md
Turning to the reference for a quick brush-up of my knowledge, I stumbled upon this peculiar grammar in the mutability paragraph. Attempt to correct it, keeping its original meaning.
=> expressions.md: Attempt fixing broken grammar in Mutability paragraph

src/patterns.md, src/tokens.md
This PR documents RangeFrom-style patterns as a prelude to stabilizing https://github.com/rust-lang/rust/issues/67264, per the stabilization policy.
=> Document RangeFrom patterns

src/attributes/limits.md
The macro syntax without the semicolon is not valid.  This updates it so that it is valid syntax.
=> Fix recursion_limit example.

src/items/generics.md
Changed the slices link to refer to slice.md rather than array.md
=> Fixed link typo in Generics.md

src/type-coercions.md
There are definitions of subtrait and supertrait, so use the
official terminology.
=> Use subtrait/supertrait, not sub-trait, super-trait.

src/special-types-and-traits.md
Numeric types, char, bool, `!`, shared references, and raw pointers all have ordinary Copy impls in std, not
provided by the compiler. Also, mention closures here.
=> Update list of types with magic Copy impls

src/crates-and-source-files.md
I think the underscore is correct, not the hyphen
```rust
#![crate_name = "foo-bar"]
fn main() {
println!("Hello, world!");
}
```
```bash
$ rustc src\main.rs
error: invalid character `-` in crate name: `foo-bar`
--> src\main.rs:1:1
|
1 | #![crate_name = "foo-bar"]
| ^^^^^^^^^^^^^^^^^^^^^^^^^^
error: aborting due to previous error
```
```rust
#![crate_name = "foo\u{002D}bar"]
fn main() {
println!("Hello, world!");
}
```
```bash
$ rustc src\main.rs
error: invalid character `-` in crate name: `foo-bar`
--> src\main.rs:1:1
|
1 | #![crate_name = "foo\u{002D}bar"]
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
error: aborting due to previous error
```
`#![crate_name = "foo_bar"]` is no error
`#![crate_name = "foo\u{005F}bar"]` is no error
=> fix crate_name attribute description

src/tokens.md
Current definitions of byte characters and byte literals do not allow escaped
single and double quotes. Updated lexical syntax for byte characters and
strings to allow these characters. This is in sync with the implementation.
=> Byte literal and string syntax: add missing quote escapes

src/subtyping.md
This will allow the example to be built under edition 2021.
=> Update 'Subtyping and Variance' example to use `dyn Trait` syntax

src/types/trait-object.md
Closes #1070.
This patch leaves the grammar block describing `dyn` as an optional keyword, treating the 2021-edition rejection of missing `dyn` as a post-parsing error (which is after all how it's implemented).
I think that's consistent with how the grammar works elsewhere: it describes what's allowed in any edition, while the text outside 'Edition Differences' blocks describes what's allowed in all editions.
=> Say that bare trait objects are rejected in the 2021 edition

src/patterns.md
=> Say that `...` range patterns are rejected in the 2021 edition

README.md
Makes things easier for would-be contributors,
though sometimes it might just tell them that
mdbook doesn't support what they wanted to do.
=> README.md: link to mdbook docs

src/inline-assembly.md
This came up in a discussion on Zulip.
cc @joshtriplett
=> Clarify behavior of x87 FP registers in inline assembly

.github/workflows/main.yml, STYLE.md, book.toml
This changes book.toml as requested in #1065, and updates the Github Actions to use a new enough version of mdBook.
I've also suggested an update to the part of the style guide that talks about edition annotations on examples.
Closes #1065
=> Switch the default edition for examples to 2021

src/tokens.md
Closes #1069.
I believe this is a correct description of what was implemented in rust-lang/rust#84599 .
I haven't tried to make use of the Reference-level explanation section from RFC3101, which I think doesn't capture what was implemented (for example, it doesn't indicate that `continue'label` is now rejected).
This PR leaves reserved prefixes undocumented in the Lexer rules blocks, but I hope that's acceptable for now (suffixes for string literals are already missing there).
=> Document syntax reserved in Rust 2021

src/identifiers.md
This is following on from discussion in PR #1128.
UAX31 says an implementation that uses a variant of the default rules should
>  declare that it uses a **profile** and define that profile with a precise specification of the characters that are added to or removed from Start, Continue, and Medial and/or provide a list of additional constraints on identifiers. 
so I suppose this counts as such an additional constraint.
=> State in the UAX31 profile description that a lone `_` is not an identifier

src/macros-by-example.md
=> Say that macros-by-example `ident` metavariables can match raw identifiers

src/macros-by-example.md
Metavariable names are not necessarily identifiers: they may also be keywords,
raw identifiers or `_`.
=> Improve the documentation of macros-by-example metavariable names

src/macros-by-example.md
Closes #1072
I've tried doing it with explicit "Edition Differences" blocks.
I've included a change under Follow-set Ambiguity Restrictions too.
I took some of the wording from parts of PR #957 which were left out at the time.
Do you think it's worth adding a note mentioning that the relevant edition
is the one in effect where the macro is defined, as opposed to invoked?
=> Document the 2021 edition changes to macros-by-example `pat` metavariables

src/SUMMARY.md, src/expressions.md, src/expressions/operator-expr.md, src/expressions/underscore-expr.md, src/macros-by-example.md, src/tokens.md
Adds documentation for the `destructuring_assignment` feature (https://github.com/rust-lang/rust/issues/71126), which is accepted for stabilisation (https://github.com/rust-lang/rust/pull/90521). The documentation is based on the [RFC text](https://github.com/rust-lang/rfcs/blob/master/text/2909-destructuring-assignment.md#reference-level-explanation).
=> Document destructuring assignment

src/patterns.md
Removes complexity in `PathPattern` spec introduced by splitting `PathExpression` into its subcomponents `PathInExpression | QualifiedPathInExpression`, replaces the same segment by `PathPattern` in `RangePatternBound`.
=> (minor) Remove Expression Path sub-types splits in Pattern specs

src/items/functions.md
Span the link along the whole "const contexts", the text looks unnatural when the last `s` is left out of the hyperlink.
=> Improve rendering

src/items/constant-items.md
I think the section about associated constants is more informative
than the glossary definition for the word "associated" in this case.
=> Link to associated constants section rather than glossary

src/items/associated-items.md
Since const panics are now [stabilized], I figure it would be good to
document some of its gotchas. I couldn't really find documents for
the specifics I ran into. I am no const eval expert, and what I
wrote is basically a paraphrase of Ralf's comments[^1][^2],
but I hope to get the ball rolling for adding some docs.
I deliberately chose to not mention the guarantee about syntactically
referenced constants in functions that require code generation as it
seems hard to explain completely without some ambiguity. It also seems
to me that the rules are not completely stable[^3][^4] yet.
[stabilized]: https://github.com/rust-lang/rust/issues/89006
[^1]: https://github.com/rust-lang/rust/issues/91877#issuecomment-995026270
[^2]: https://github.com/rust-lang/rust/issues/91877#issuecomment-995977016 …
=> Note difference in CTFE timing between associated and free constants

src/items/functions.md
**This Commit**
Changes "callers responsibility" to "caller's responsibility".
**Why?**
Just saw it while reading and figured it was a typo.
=> Fix micro typo in async/unsafe function docs

src/macros-by-example.md
Viewing the repository locally on VSCode's markdown preview shows an error at that position
Adding backticks fixes the issue
=> (minor) Add backticks to token

src/expressions/struct-expr.md
`StructExprField` may use outer attributes: https://replit.com/@pushkine/Attributes-in-Struct-Expressions#src/main.rs
Here's an occurrence in rust's compiler:
https://github.com/rust-lang/rust/blob/a00e130dae74a213338e2b095ec855156d8f3d8a/compiler/rustc_data_structures/src/sync.rs#L571-L577
=> Add undocumented outer attributes above StructExpr fields

src/patterns.md
Changes the allowed right hand side pattern from `Pattern` to `PatternNoTopAlt`
`ident @ A | B` is always parsed as `[ident @ [A]] | [B]`
Even using the optional heading `|` throws an error
```rs
match () {
a @ | _ | _ => {}
//      ^ expected a binding pattern
}
```
=> Update patterns allowed in @ patterns

src/items/generics.md
[stabilisation report](https://github.com/rust-lang/rust/pull/90207#issuecomment-958843546) for this feautre
cc @rust-lang/project-const-generics
=> document `#![feature(const_generics_defaults)]`

src/items/associated-items.md
@RalfJung pointed out in a [comment] that the previous phrasing of the
sentence can read like it is giving guarantees about free constant
definitions always undergoing CTFE, even when unused. That seems to be
how the compiler behaves right now, but it's unclear whether it's
intentional.
Be more precise and don't talk about free constants at all.
---
Related to this, I'm not sure if https://github.com/rust-lang/rust/issues/89006
stabilized the fact that *unamed constants* (in contrast to named but unused free constants) always undergo CTFE. It's part
of the issue, and it's used in the release notes to demo the feature, so I had assumed that it does. Going through the RFC and the issue though, it does not state it explicitly, so it's possible that nothing with regards to when CTFE is …
=> Improve associated constant item CTFE timing section

src/expressions/operator-expr.md, src/glossary.md
Since <https://github.com/rust-lang/rust/pull/89488> it was moved to a different directory.
=> Fix link to the Bastion of the Turbofish

src/attributes/codegen.md
This macro has recently been updated and we hope for it to be stabilised soon.
=> Mention std::is_aarch64_feature_detected

src/expressions/method-call-expr.md
Closes #1068
This behaviour is also documented in the standard library docs for the [array type][1].
[1]: https://github.com/rust-lang/rust/blob/ad88831cd50ffe9cb9006bbdcb7fc9d97142e410/library/std/src/primitive_docs.rs#L585
The edition guide doesn't say that the special-case behaviour applies when the array type is reached via deref coercions, but this is clear from the implementation. It's also mentioned in https://github.com/rust-lang/rust/pull/84147#issuecomment-819000436.
=> Document pre-Rust-2021 special case for IntoIterator method lookup

src/inline-assembly.md
This seeks to limit the directives guaranteed to be supported by inline assembly to a subset of those supported by LLVM and GNU AS. The list is chosen as a compromise between utility and implementability, and may be increased in the future.
See discussions here:
<https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/asm!.20and.20backends> and <https://rust-lang.zulipchat.com/#narrow/stream/216763-project-inline-asm/topic/Defect.20Report.3A.20GNU.20AS.20support>
CC: @joshtriplett
=> Add supported Directives list

src/inline-assembly.md
See: https://rust-lang.zulipchat.com/#narrow/stream/216763-project-inline-asm
The current supported directives list has `.intel_syntax` and `.att_syntax` without options supported, and claims them to be the default option (for no `att_syntax` option vs. `att_syntax` option). However, the default behaviour of the `.intel_syntax` directive differ between llvm-mc and gnu as, and GNU AS differs from the guaranteed behaviour: See https://godbolt.org/z/3js4Pfds7 (GNU AS) vs. https://godbolt.org/z/rKhqPxKvr (llvm-mc).
This PR removes the guaranteed support for the no-parameter form of`.intel_syntax`, and from `.att_syntax` as well to mirror.
=> inline-asm.md. Fix `.intel_syntax` directive

src/const_eval.md
We are in the process of stabilizing `const_fn_fn_ptr_basics` and `const_fn_trait_bound` (see https://github.com/rust-lang/rust/pull/93827). This edit updates const_eval.md to reflect the new capabilities after stabilizing these features.
=> Update const_eval.md for feature stabilization

src/attributes/codegen.md, src/behavior-considered-undefined.md
=> update UB list for safe target_feature

src/tokens.md
The token `~` is a valid punctuation token inside macro invocations and macro rule declarations: https://replit.com/@pushkine/Tilde-token#src/main.rs
=> Add undocumented Punctuation token Tilde `~`

src/destructors.md
This is being discussed in https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/Guarantees.20around.20Drop.20.28.2390752.29.
=> Try to clarify destructor not being run scenario.

src/attributes/codegen.md
Draft documentation update https://github.com/rust-lang/rust/issues/90620
Of note is the fact that I haven't documented the "v8.Xa" target features in order to discourage their use. It's much better to use the more granular target features available.
=> Document aarch64 `target_feature` options

src/attributes/codegen.md
Related stabilization PR: https://github.com/rust-lang/rust/pull/93745
=> Document ADX `target_feature`

theme/reference.css
Other scopes have a semicolon at end of their scopes, but these two do not have one.
=> Fixed inconsistency in the usage of semicolon at end of scopes

src/expressions/literal-expr.md, src/tokens.md
This documents integer and floating-point literal expressions, and improves the docs for integer and floating-point literal tokens.
Covers some of #939, for integer and floating-point literals.
Covers the RFC 0879 part of #298, and some of the RFC 0463 part (ie, for numeric literals but not string literals).
The details of floating-point conversion deserve a more throrough description, but maybe that needs looking at together with the standard library docs.
I had a false-positive error from linkchecker; the last commit is a workaround for that, but I think the right thing would be an addition to `LINKCHECK_EXCEPTIONS` in `linkcheck/main.rs`.
=> Numeric literal expressions and literal suffixes

src/items/external-blocks.md
This is an accompanying PR for linking modifier stabilization in https://github.com/rust-lang/rust/pull/93901.
=> Document native library modifier syntax and the `whole-archive` modifier specifically

src/procedural-macros.md
This PR assumes https://github.com/rust-lang/rust/pull/92472 is merged.
=> Document compatibility between declarative and procedural macro tokens

src/expressions/literal-expr.md, src/expressions/operator-expr.md
This describes what's going on if you write something like `-128_i8`: it invokes a no-op unary negation (taking -128 to -128), which the reference currently says should panic when overflow checks are enabled.
In fact this situation is special-cased so that there is no panic.
As I understand it, it's implemented by folding the expression to a constant during conversion from HIR to THIR, before the overflow checks are inserted (when THIR is lowered to MIR).
There are comments about it here:
https://github.com/rust-lang/rust/blob/ec7b753ea91d8a5640388ea74fd231f91394ee9d/compiler/rustc_mir_build/src/thir/pattern/mod.rs#L563
=> Document that unary negation of a signed integer literal cannot cause an overflow error

src/expressions/literal-expr.md, src/patterns.md, src/tokens.md
Closes #1167
This removes the `BOOLEAN_LITERAL` token, as `true` and `false` are already listed as keywords.
Then fills in the "Boolean literal expressions" section (one more small piece of #939).
=> Boolean literal expressions

src/attributes/codegen.md, src/inline-assembly.md
As discussed in https://github.com/rust-lang/rust/pull/91608
At the very least, which feature to use for assembly should be clear.
=> Update aarch64 to use neon as fp

src/attributes/testing.md, src/crates-and-source-files.md, src/special-types-and-traits.md
Closes #1193
There doesn't seem to be a satisfactory way to document when tests are considered to pass: the implementation checks whether `ExitCode::to_i32()` returns 0, but `to_i32()` is intentionally hidden and marked as perma-unstable, and nothing in `ExitCode`'s docs provides a notion of a "successful" code.
So I've vaguely said "whether the resulting `ExitCode` represents successful termination", and listed some specific cases.
=> Document the Termination trait for main() and test functions

src/type-layout.md
Clarify that `repr(packed)` minimizes inter-field padding and, in the special case of `repr(packed(1))`/`repr(packed)`, guarantees no inter-field padding.
=> Clarify guarantees provided by repr(packed)

src/linkage.md
As a crate-level attribute, this must be used as an inner attribute.
=> Fix crate_type attribute examples

src/inline-assembly.md
This was added by https://github.com/rust-lang/rust/pull/95740.
=> Inline assembly: Add kreg0 register class

src/patterns.md
The use of `PathPattern` instead of `PathExpression` in `RangePattern` is IMO confusing, since these values are not patterns and are not represented as patterns in the AST.
=> Don't use PathPattern in RangePattern bounds

src/items/use-declarations.md
#1115 asks for an example of a `use` declaration inside of a function. I think the easiest way to do that is to move the already existing declaration inside of the `main` function.
Closes #1115
=> Moved the option variant imports

src/items/functions.md
Closes #1197
I don't think there's anything to do other than remove the claim in the text that these are forbidden. The grammar already allows it.
rust-lang/rust#64926 says this is stabilised only for the "Rust" and "C" ABIs, but I think that would be better covered in documentation for particular ABIs, if/when that exists.
=> Stop saying that const functions cannot use 'extern'

src/expressions/match-expr.md
As per issue #1213 , `#[cold]` only applies to functions.
=> Update "Match Expressions" to remove 'cold'

src/names/namespaces.md
This cross-namespace warning is being removed in https://github.com/rust-lang/rust/pull/96296.
=> Remove footnote on warning about lifetime shadowing labels.

src/inline-assembly.md
This documents the availablity of the tmm registers for clobbers in inline assembly for x86-64. It also documents that they are clobbered by the x86-64 abi_clobbers.
=> Add tile registers to inline-assembly documentation

src/inline-assembly.md
For `lateout` and similar operand direction specifiers, a quoted argument must be an explicit register name, per the EBNF grammar we give. As such, we should not use quotes when describing syntax used with register classes.
Further, correct the EBNF: in EBNF, quoted strings are always terminals, but `"<explicit register>"` is intended to be a nonterminal surrounded by literal (terminal) quotation marks. Moving the quotes to their own terminal symbols does require escaping, but makes the terminal/nonterminal distinction clearer. The only other place double-quotes are present in the grammar is inside `STRING_LITERAL`/`RAW_STRING_LITERAL`, so calling attention to this case is worthwhile for clarity.
=> Inline assembly: Clarify references to quoted regs

src/const_eval.md
Since Rust 1.61.0 it is possible to do unsizing casts in const context, so reflect that in reference.
=> Reflect changes about unsizing casts in const context

src/items/external-blocks.md
This is an accompanying PR for `bundle` stabilization in https://github.com/rust-lang/rust/pull/95818.
=> Document native library modifier `bundle`

src/macros-by-example.md
Requested in https://github.com/rust-lang/rust/pull/95860
=> Add stable references of `macro_metavar_expr`

src/subtyping.md
Given `fn(T) -> T` the type `T` is only invariant while wrapped inside of an item. If you have `fn(T) -> T` directly you can freely "shrink" the `T` in return position or "grow" the `T` in argument position. E.g.
```rust
fn split_lt<'a, 'short, 'long>(
value: fn(&'a ()) -> &'a (),
) -> fn(&'long ()) -> &'short ()
where
'a: 'short,
'long: 'a,
{
value
}
```
=> modify confusing variance example

src/tokens.md
The previous version just said "whitespace at the beginning of the next 
line is ignored", but that is not quite correct. Currently, exactly four
characters are ignored in that position. This is different from the
definition of `char::is_whitespace` and `char::is_ascii_whitespace`.
Additionally "at the beginning of the next line" is confusing as 
additional \n are also ignored.
See the lexer implementation:
https://github.com/rust-lang/rust/blob/595088d602049d821bf9a217f2d79aea40715208/compiler/rustc_lexer/src/unescape.rs#L281-L287
https://github.com/rust-lang/rust/blob/595088d602049d821bf9a217f2d79aea40715208/compiler/rustc_lexer/src/unescape.rs#L300-L307
=> Clarify "string continue" for (byte) string literals

src/types.md
This sentence was written over a decade ago by Graydon: https://github.com/rust-lang/rust/commit/293678847b8c6291389826b1a7e9c5bda889c8d9#diff-dee91bf0fc1779efb1cef2b9bcb1f296c8cc0bcb6597a4f008b33e21a44a5ad3R986-R988
As far as I can tell, no such restriction has existed since Rust 1.0.
=> Remove outdated restriction on recursive types

src/runtime.md
The reference documents the syntax of the `windows_subsystem` attribute but neglects to describe what it's intended to do. This is my attempt to rectify that.
=> Describe what `windows_subsystem` does

src/behavior-considered-undefined.md
This is the underlying UB that https://github.com/rust-lang/rust/pull/95252 and https://github.com/rust-lang/rust/pull/95295 fix.
I also removed the statement 
> if the span is empty, "dangling" is the same as "non-null"
since it contradicts what [the library docs](https://doc.rust-lang.org/nightly/std/ptr/index.html) say about zero-sized accesses/types.
=> clarify that references size_of_val can never exceed isize::MAX

src/items/unions.md, src/types/union.md
Cc https://github.com/rust-lang/rust/pull/97995#issuecomment-1186263679
r? @ehuss
=> update union field type rules

src/expressions.md, src/expressions/operator-expr.md
as requested by @Havvy 
This is a bit unusual for being exposed as a library feature, fut it really is a fundamental language feature without stable syntax, which is stably accessible through the standard library.
=> document raw-addr-of operators

src/macros-by-example.md
Reverts rust-lang/reference#1192
(requested on https://rust-lang.zulipchat.com/#narrow/stream/237824-t-lang.2Fdoc/topic/revert.20.24.24/near/290445319)
=> Revert "Add stable references of `macro_metavar_expr`"

src/comments.md, src/interior-mutability.md, src/items/functions.md, src/statements-and-expressions.md, src/types/pointer.md, src/visibility-and-privacy.md
This is mentioned specifically in the style guide.
=> Remove uses of the phrase "in Rust"

src/expressions/await-expr.md
As requested in https://github.com/rust-lang/rust/pull/98718#issuecomment-1171749755. Thanks!
r? @ehuss 
- [Current `.await` desugaring code in the compiler](https://github.com/eholk/rust/blob/3268bf1d31227d0422c90b2259e67ba12ed19e3f/compiler/rustc_ast_lowering/src/expr.rs#L594-L608)
=> Add `IntoFuture::into_future` desugaring

src/expressions/array-expr.md
The related issue is closed : https://github.com/rust-lang/rust/issues/74836
=> Remove outdated warning

src/SUMMARY.md, src/attributes/type_system.md, src/const_eval.md, src/destructors.md, src/expressions.md, src/expressions/block-expr.md, src/expressions/if-expr.md, src/expressions/loop-expr.md, src/expressions/struct-expr.md, src/names.md, src/names/namespaces.md, src/patterns.md, src/tokens.md
=> Add `let_chains` references

src/items/external-blocks.md
Same as https://github.com/rust-lang/rust/pull/100074, but for the reference.
=> Be less specific about the representation of `+bundle`

src/SUMMARY.md, src/attributes/type_system.md, src/const_eval.md, src/destructors.md, src/expressions.md, src/expressions/block-expr.md, src/expressions/if-expr.md, src/expressions/loop-expr.md, src/expressions/struct-expr.md, src/names.md, src/names/namespaces.md, src/patterns.md, src/tokens.md
Reverts #1179 because let-chains are getting unstabilized in rust-lang/rust/#100538
=> Revert let chains reference docs

src/attributes/type_system.md
Fixes: #1250 
Adding missing documentation after changing in rust-lang/rust#91161 (rust-lang/rust#92744)
=> #[non_exhaustive] on variant blocks cross-crate as casts

src/attributes/testing.md, src/crates-and-source-files.md
rust-lang/rust#97803 in Rust 1.63 added some implementations of `Termination`; I think it's worth updating the notes in the Reference to match.
=> Update examples of what implements `Termination`

src/expressions/block-expr.md
* fix "typo" when declaring semantics of `return` from within async block
* remove confusing false comment from the example
=> Clarify reference on async blocks

src/type-layout.md
The reference currently states that "[t]he size of a value is always a multiple of its alignment." This might be taken to imply that a type's size is greater than or equal to its alignment. This commit clarifies that 0 is a valid multiple; zero-sized types have 0 size and nonzero alignment.
=> Clarify that 0 is a valid multiple of a type's alignment

src/expressions.md
If rustc's behavior regarding async blocks is intentional, then this fixes #1267.
We might want to consult with the Async WG on this first. Edit: [Zulip topic](https://rust-lang.zulipchat.com/#narrow/stream/187312-wg-async/topic/syntax.20of.20async.20blocks/near/298263840).
=> Classify AsyncBlockExpression as ExpressionWithoutBlock

src/type-layout.md
=> Specify guarantees for repr(rust) structs

src/attributes.md, src/items/external-blocks.md
* Documents the `raw-dylib` link kind (https://github.com/rust-lang/rust/issues/58713), including how it differs from `dylib`.
* Documents the `link_ordinal` attribute (https://github.com/rust-lang/rust/pull/89025).
=> Add documentation for raw-dylib and link_ordinal

src/attributes/diagnostics.md
Clippy warns if the `since` version in `#[deprecated]` isn't semver-compliant. This PR updates an example using `#[deprecated]` to make the version semver-compliant.
=> Use semver-compliant example version

src/patterns.md
This switches the style of the patterns chapter from newlines after N characters to one sentence per line.
=> One sentence, one line Patterns chapter

src/expressions/block-expr.md, src/expressions/loop-expr.md
=> Document `label_break_value` in the reference

src/items/functions.md, src/statements.md
For the stabilization of `let else` statements.
Tracking issue: https://github.com/rust-lang/rust/issues/87335
=> Document let else statements

src/expressions.md, src/statements-and-expressions.md, src/statements.md
Mechanical PR that converts the expressions chapter to having one sentence per line.
=> One line one sentence for expressions and statements main chapters

src/items/associated-items.md, src/items/traits.md, src/items/type-aliases.md
There really isn't a *ton* to add here. Almost all of the syntax related to GATs falls out from existing syntax.
=> Add basic GATs reference information

src/inline-assembly.md
Tracking issue: https://github.com/rust-lang/rust/issues/93333
=> Add `sym` operands for inline assembly

src/patterns.md
This fulfills the reference PR requirement for https://github.com/rust-lang/rust/pull/102275
When looking at this PR, you will have to look at the commits individually. The first one swaps the style of the page to one sentence per line.
But also, before this can be merged, the question I raised in https://github.com/rust-lang/rust/issues/67264#issuecomment-1241356008 needs to be answered, although it does not substantially affect the rest of the prose w.r.t. a review.
=> Document Half Open Range Patterns + Improve Range Patterns in General

src/macros-by-example.md
Since this is a subtle idiosyncracy into which macro users sometimes bump, it can be incredibly helpful to give them a pin-pointed link to the exact paragraph talking about this. Hence the idea of adding some kind of header, and thus an anchor, to it. Since it's just a paragraph, I've gone for a very low header, such as h4.
cc @nilstrieb
=> Add an anchor to the "forwarding macro fragments" paragraph

src/comments.md
Currently this reference marks up e.g.
```rust
fn main() { //
println!("Hello, world!");
}
```
as
```
fn main() { <comment-start>//
println!("Hello, world!");<comment-end>
}
```
because the ~\[`/` `!`] rule allows a newline to sneak in before the ~`\n`*
=> Disallow newline directly following `//`

src/attributes.md, src/attributes/codegen.md
As part of the stabilisation work: https://github.com/rust-lang/rust/issues/74727 this PR adds some documentation for the instruction set attribute. I've popped this in the codegen attributes as that seemed rather self-explanatory. It's currently fairly brief but feels "enough" to me, enough at least to get some feedback on iterate on.
=> Document RFC 2867: instruction_set attribute

src/behavior-considered-undefined.md
This makes explicit some de-facto rules that existed at least since Rust 1.0:
- Boxes also have aliasing requirements.
- References must outlive functions they are passed to. (It is not *entirely* clear that this was intended when the `dereferenceable` attribute was added, given that the attribute was also added to `Box` which can definitely be deallocated by functions they are passed to. But when that got fixed in https://github.com/rust-lang/rust/issues/66600, nobody suggested to also remove the attribute from references.)
Irrespective of whether we actually *want* these rules, they *do* reflect our current requirements and code not following them risks miscompilations. As such I think we should document them here and consider them the baseline for changes to the aliasing model. It's …
=> update aliasing rules section of the reference

src/expressions/literal-expr.md, src/tokens.md
Closes #298, Closes #1304
This reflects the changes made in in rust-lang/rust#102944 .
Previously, unknown suffixes were rejected by the parser. Now they are accepted by the parser and rejected at a later stage.
Similarly, integer literals too large to fit in u128 are now accepted by the parser.
Forms like `5f32` are now `INTEGER_LITERAL` rather than `FLOAT_LITERAL`.
The notion of a 'pseudoliteral' is no longer required.
This PR also fixes a couple of related bugs, and adds suffixes to the 'Lexer' blocks for non-numeric literals.
=> Update literal suffix docs for rust-lang/rust#102944

src/items/external-blocks.md
This is an accompanying PR for `verbatim` stabilization in https://github.com/rust-lang/rust/pull/104360.
=> Document native library modifier `verbatim`

src/items/extern-crates.md
The `crateid` term or attribute is replaced with `crate_name` in [chapter crates and source files](https://doc.rust-lang.org/reference/crates-and-source-files.html#the-crate_name-attribute). It was originally proposed in [RFC0109](https://rust-lang.github.io/rfcs/0109-remove-crate-id.html) and merged in [PR109](https://github.com/rust-lang/rfcs/pull/109)
=> replace `crateid` term with `crate_name`

src/special-types-and-traits.md
The (implicit) type parameter `Self` in traits is not `Sized` by default but the current documentation is not very clear about it.
> All type parameters have an implicit bound of `Sized`. […] The one exception is the implicit `Self` type of a trait.
Source: [Documentation of `std::marker::Sized`](https://doc.rust-lang.org/nightly/std/marker/trait.Sized.html):
It's *except `Self` **in traits*** specifically since e.g. the “sizedness” of `Self` in *structs* depends on the sizedness of the last field.
---
As an aside, in general not much is written about `Self` in the reference. That's why I chose this specific location in the docs.
=> Document that type parameter `Self` is unsized by default

src/const_eval.md, src/expressions/operator-expr.md, src/items/enumerations.md, src/type-layout.md
Continuation of #639. This should only be merged after the feature is stabilized.
=> Update documentation for arbitrary_enum_discriminant feature

src/trait-bounds.md
```rs
fn f<A> where A: Copy () {} // ->
fn f<A>() where A: Copy {}
```
The former isn't valid Rust as far as I can tell, though I may be missing something.
```
Compiling playground v0.0.1 (/playground)
error: expected `(`, found keyword `where`
--> src/lib.rs:1:9
|
1 | fn f<A> where A: Copy () {}
|         ^^^^^ expected `(`
error: could not compile `playground` due to previous error
```
=> Syntax correction for trait-bounds.md

src/destructors.md
It's unclear what this bullet means. If it means a match guard, that is covered in the line above. If it referred to the scrutinee, that would be wrong. I don't think it's possible to embed an expression inside of a match arm _pattern_.
This came up in the [lang team triage meeting][meeting].
[meeting]: https://hackmd.io/JACzq-ssT4qtH0DS3B8nQQ?both#%E2%80%9CIntroduce-terminating-scope-for-tail-expressions-of-breakable-scopes%E2%80%9D-rust106493
=> Reword "expression for a match arm"

src/linkage.md
I thought it wanted to be "at least once", but it could also have wanted to be "immediately". Either way, it seems not important.
=> remove confusing words

src/behavior-considered-undefined.md
`addr_of!(&_)` is a double-address-of... no idea what I was thinking when writing this, probably it's just a typo.
=> fix place expression context example

src/patterns.md
As described in #1329, the Reference's current use of this terminology does not match rustc's use.
Following the core::ops trait terminology (as is already done for [RangeExpression](https://doc.rust-lang.org/1.67.0/reference/expressions/range-expr.html)) results in a clearer grammar.
Closes #1329.
=> Eliminate 'half open' terminology from range pattern grammar

src/attributes/codegen.md
Stabilization PR:
+ https://github.com/rust-lang/rust/pull/106774
=> Document `cmpxchg16b` target feature

src/items/unions.md
Hi! Found a tiny typo. Although not a 100% certain this fix is correct, the sentence reads much clearer this way.
=> fix: Typo/reference

src/attributes/codegen.md
Counterpart to rust-lang/rust#107711
=> Document movbe target feature

src/items/constant-items.md
See https://github.com/rust-lang/rust/issues/93838
It seems like everyone is onboard with blessing this (useful) behavior as stable.
=> Clarify that free constants are always evaluated at compile time

src/expressions/loop-expr.md, src/names/namespaces.md
* list labeled blocks in the namespaces page
* add an example
* improve wording
=> Improve labeled blocks documentation

src/inline-assembly.md
This updates the reference to match the changes in rust-lang/rust#105798
=> Relax ordering rules for `asm!` operands

src/inline-assembly.md
This sort of thing may seem "obvious", but in practice people often have high expectations of Rust. They expect safety even in highly `unsafe` circumstances, as Rust does in fact offer that. This feature of the language is an exception, as it amounts to allowing the programmer to talk as directly to the machine as possible. So, it is time to explain that we ask for nothing from the assembler, only correct assembling of correct assembly.
=> Explain typos in `asm!` can be unsound

src/inline-assembly.md
This test does not work on aarch64 platforms, so this disables it for non-x86_64 platforms.
=> Fix example for non-x86 targets

src/keywords.md
Closes #1348
There are no other two-word keywords, so I'm not sure whether `KW_MACRO_RULES` or `KW_MACRORULES` is better; I used the former.
=> Add an entry for macro_rules in the "Weak keywords" lexer block

src/procedural-macros.md
A comment in the procedural macros chapter had a space that meant it was wrongly annotating what a piece of code would output.
=> fixed minor error in a comment that annotated output of a proc macro

src/items/external-blocks.md
The `raw-dylib` feature (#58713) is being stabilized for x86:
* Remove the note about `raw-dylib` not working on x86.
* Document the `import_type_name` key for the `link` attribute.
=> Update raw-dylib documentation for stabilization

src/types/impl-trait.md
Tiny fixes for invalid code examples in the [`impl` docs](https://doc.rust-lang.org/reference/types/impl-trait.html#differences-between-generics-and-impl-trait-in-return-position).
=> Fix example code in `impl` docs

src/inline-assembly.md
This PR is a sub-part of https://github.com/rust-lang/rust/pull/111235, to move LoongArch from unstable to stable inline-assembly documentation.
=> Add LoongArch to inline-assembly documentation

src/expressions/call-expr.md
=> Fix inconsistent formatting of Disambiguating Function Calls example

src/paths.md
The current syntax allows for invalid paths, such as:
- `hello::world::` as the trailing `::` would be caught by the incorrectly mapped option
- `hello::::world` as the first `::` would be caught by the incorrectly mapped option
This PR fixes these ambiguities.
=> fix incorrect syntax for type-paths

src/conditional-compilation.md
This was changed in rust-lang/rust#110141.
=> Document the ordering behavior of crate cfgs

src/type-layout.md
Issue https://github.com/rust-lang/rust/issues/27060 has been resolved, so it is no longer possible to safely create unaligned pointers to packed struct fields.
=> Remove obsolete note about soundness hole in type-layout.md

src/types/never.md
Remove unstable feature of never type from doc
---
https://doc.rust-lang.org/reference/types/never.html
Gives example which is unstable
```
let x: ! = panic!();
// Can be coerced into any type.
let y: u32 = x;
```
But not giving example for what has been stabilized
```
extern "C" {
pub fn abort() -> !;
}
```
This is really confusing for newcomers:
1. The Rust reference does not mention unstable feature, except this one
2. The doc says
> NB. The never type was expected to be stabilized in 1.41, but due to some last minute regressions detected the stabilization was temporarily reverted. The ! type can only appear in function return types presently. See [the tracking issue](https://github.com/rust-lang/rust/issues/35121) for more details.
Some people stops reading when they realize never …
=> Remove doc of unstable feature of never type

src/expressions/operator-expr.md
Say that the note applies to integer division only (compare the note about rounding to zero).
Addresses #1375
=> Operator expressions: make the note about division by zero clearer.

src/behavior-considered-undefined.md
Cc @rust-lang/wg-const-eval @rust-lang/wg-unsafe-code-guidelines  -- I think that is the only extra const UB but let me know if I missed anything. :)
=> mention the extra const UB

src/behavior-considered-undefined.md
I personally found this description of UB confusing, since the use of "reached" suggests that UB only happens for read bytes, and the definition of immutability is not given, allowing for multiple interpretations: does the "data" have to be immutable from the first read? From the creation of the reference? Between reads from the immutable accessor, but not otherwise? etc.
This clarifies the actual UB conditions, based on [this Zulip interaction](https://rust-lang.zulipchat.com/#narrow/stream/136281-t-opsem/topic/What.20exactly.20are.20.22immutable.22.20and.20.22reached.22.20in.20shared.20ref.20UB.3F) and [this reference discussion](https://github.com/rust-lang/reference/issues/1227) in two ways:
* The definition of "data" is clarified to be stated in terms of bytes, in a way that should …
=> Clarify UB around immutability & mutation

.github/workflows/main.yml
The merge queue is currently firing off two jobs in parallel doing the exact same thing. My understanding is that this is because there is one trigger (merge_group) for the creation of the merge queue entry, and another trigger (push) for the push that GitHub does to a temporary branch to do the merge.
The solution here is to just drop the "push" trigger. I don't think that trigger is very useful now with the merge queue. It only makes sense if someone is creating new branches directly in this repo, and wanting to run CI jobs directly on those branches. For one, I don't think people should be creating branches here. Second, even if they do, I don't think they really need to run CI (PRs are good enough for that).
=> Fix merge queue building twice.

src/attributes/codegen.md
~~This updates the `instruction_set` attribute entry to more clearly explain the additional restrictions that the attribute places on inlining. Since Rust performance heavily relies on inlining, it's actually a fairly big deal to document it.~~
~~Pinging @pnkfelix as the liaison for the `instruction_set` attribute during its development.~~
~~This explanation is actually slightly looser than the explanation given in the RFC: this explanation allows inlining between no-attribute code without inline asm and other code. So, T-lang should likely approve the update with an FCP or similar process. The intent is that once this is approved as the documentation for how the attribute works then https://github.com/rust-lang/rust/pull/104121 (which updates the MIR inliner to match these rules) will be …
=> Clearly specify the `instruction_set` effects

src/trait-bounds.md
cc https://github.com/rust-lang/rust/pull/100747/files#r962488178
=> add section about implied bounds

src/conditional-compilation.md
As an embedded dev who uses Windows at work, it physically pains me when people use `#[cfg(target_os = "unix")]` when they actually mean `#[cfg(not(target_os = "none"))]`. Hopefully this will increase awareness that "none" is a valid `target_os`.
=> conditional-compilation.md: Mention the "none" target_os value

src/type-layout.md
See rust-lang/rust#114201 for context.
=> Update section on default layout for `repr(Rust)`

src/type-layout.md, src/types/boolean.md, src/types/numeric.md, src/types/pointer.md, src/types/textual.md
Specify the bit validity and padding of the primitive numeric  types, bool, char, and pointer and reference types.
Closes #1291
=> Specify bit validity and padding of some types

src/behavior-considered-undefined.md
It was pointed out to me that the docs currently say that the things on the UB list are definitely UB. That's not true, we do reserve the right to have less UB in the future. (Exactly that is happening e.g. in https://github.com/rust-lang/reference/pull/1387.)
=> we reserve the right to reduce our amount of UB

src/attributes.md
The links to the ECMA-334 and ECMA-335 were broken, I have updated those to working links.
=> docs: Fix links to ECMA standards in `attributes.md`

src/behavior-considered-undefined.md
As discussed by @rust-lang/opsem in https://github.com/rust-lang/opsem-team/issues/9: instead of saying that `*ptr` is insta-UB for "bad" pointers, only have UB when the place is actually accessed, and when place projections go out-of-bounds.
This makes the following code (which currently has UB) legal:
```rust
let ptr = 23 as *const i32;
// `ptr` is not aligned and doesn't point to an actual allocation.
// Still, this is allowed:
let ptr = addr_of!(*ptr);
// Even with a null pointer, this is allowed:
let ptr = addr_of!(*(0 as *const i32));
```
However, the following code is still UB:
```rust
// Accessing (loading from or storing to) a place that is dangling or unaligned
let mem = 0u32;
let odd_ptr = addr_of!(mem).byte_add(1).cast::<u16>();
let _val = *odd_ptr; // pointer is 1-aligned but …
```
=> replace 'UB on raw ptr deref' with UB on place projection/access

src/destructors.md
The outermost scope is "the entire function", not "the entire function body" which is different.
=> Fix temporary drop scope for last expression.

src/items/traits.md, src/types/impl-trait.md
The section on RPITIT is kind of bare, but I'm happy to flesh it out if we want to specify how it works more.
cc https://github.com/rust-lang/rust/pull/115822#issuecomment-1731889250
=> Adjust reference for return-position `impl Trait` in trait and `async fn` in trait

src/inline-assembly.md
@Amanieu I wasn't sure about the `readonly` part of this. An acquire read is not entirely a read-only operation in terms of how it affects the machine state, e.g. it cannot be arbitrarily reordered with other reads. So I assume `readonly` blocks cannot really have "acquire" effects?
=> some asm block flags also mean there can be no fences

src/expressions/operator-expr.md, src/type-coercions.md
This encodes the behavior agreed upon in https://github.com/rust-lang/unsafe-code-guidelines/issues/288.
=> Guarantee that raw pointer conversions preserve slice element count

src/expressions/underscore-expr.md
These appear in nearly identical locations in source code and have subtly different semantics, so cross link them.
I'm not sure if this is the correct link path?
=> Reference wildcard patterns from underscore expr

src/paths.md
In a method body, a path expression consisting only of the keyword `self` resolves to the method's 'self parameter'.
(I checked PR #1052 and I think it doesn't add this case.)
=> Lone `self` in a method body resolves to the self parameter

src/items/traits.md
`async fn` in traits, and return-position `impl Trait` in traits, were stabilized by <https://github.com/rust-lang/rust/pull/115822>. The object-safety error E0038 points to the Reference, so the Reference should mention this new criterion.
=> Document object unsafety of async-fn-in-trait 

src/tokens.md
`<-` was the "move operator", removed in Rust 0.5, but is still lexed as a single token.
So I think it should be listed in the Punctuation table (like the tilde token is).
Originally reported as ferrocene/specification#452
Fixes #583
=> Document that <- is a single token

src/expressions/literal-expr.md, src/tokens.md
This fills in most of what is still missing for #939.
I haven't tried to cover C string literals at this stage, as they haven't quite settled down yet.
I haven't removed much of the text in `tokens.md` which is discussing what string literal tokens "represent" or "denote", although I think strictly speaking that applies to literal expressions rather than literal tokens.
I think the best course would be think about that after, or together with, making the Tokens chapter correct (which is #626).
=> String literal expressions

src/inline-assembly.md
@Amanieu am I correct in assuming that all other asm blocks (i.e, not marked `pure`), may loop infinitely?
=> pure asm blocks must terminate

src/tokens.md
Which moved the checking for NUL chars in C string literals earlier.
See https://github.com/rust-lang/rust/pull/119172
=> Update C-String literals to reject NUL

src/expressions/literal-expr.md, src/tokens.md
I'm not sure whether "a reference to a statically allocated [Cstr] whose array of bytes contains" is the right thing to say.
The description of the "unescaping" has come out uglier than the other cases. Maybe there will be a way to do better when it comes to documenting rfc3349.
I think this finishes #939 as far as the _Literal expressions_ page is concerned, but there's more to be done before we can say "the token literals chapter just describes the tokens".
=> C string literal expressions

src/tokens.md
A future version of mdbook will adhere to commonmark more closely, and this backslash ends up showing up as a literal backslash instead of a line break.
=> Fix markdown backslash for FLOAT_LITERAL

src/lifetime-elision.md
Hi, (warning: not a Rust expert) there was a small thing that confused me while reading:
In one of the examples in the `'static lifetime elision` section of the `lifetime-elision` chapter, I got the following error messages when trying out the explicit (non-elided) form.
Example:
```rs
// Resolved as `fn<'a>(&'a str) -> &'a str`.
const RESOLVED_SINGLE: fn(&str) -> &str = |x| x;
// Resolved as `Fn<'a, 'b, 'c>(&'a Foo, &'b Bar, &'c Baz) -> usize`.
const RESOLVED_MULTIPLE: &dyn Fn(&Foo, &Bar, &Baz) -> usize = &somefunc;
```
First case (function pointer):
```rs
error: function pointer types may not have generic parameters
--> interaction-core/src/bin/foo.rs:5:26
|
5 | const RESOLVED_SINGLE: fn<'a>(&'a str) -> &'a str = |x| x;
|                          ^^^^
|
help: consider moving the …
```
=> Fix syntax in `'static lifetime elision` section of `lifetime-elision.md`

src/items/external-blocks.md
=> Fix a typo in external-blocks.md

src/paths.md
The grammar for _TypePathFn_ was changed in https://github.com/rust-lang/rust/pull/45294 (Rust 1.25) to require parenthesis if there is more than one bound. [Here](https://github.com/ehuss/rust/blob/be1c7aad723126b2ea65543b4ceed54167b841a2/compiler/rustc_parse/src/parser/path.rs#L297-L298) is where the return type is parsed (notice that it has the `AllowPlus::No` restriction).
=> Fix grammar for TypePathFn

src/attributes/codegen.md
https://github.com/rust-lang/stdarch/issues/1432 https://github.com/rust-lang/stdarch/pull/1527
r? @Amanieu
=> Update aarch64 target feature docs to match LLVM

src/expressions/operator-expr.md
Relates #1448
I've tried to the best of my ability to reproduce the verbiage of the reference, some parts feel a bit wordy to me so any feedback would be appreciated.
To fully describe the semantics of unsized to sized pointer casts, I felt it was necessary to document that the reinterpreting sized to sized casts produce identical values. I couldn't immediately find this documented.
This is because unsized to sized pointer casts also permits a reintepreting cast in the same sweep (such as `*const [u8] as *const u32`).
=> Clarify semantics of the various pointer to pointer casts

README.md, rust-toolchain.toml
We spent a lot of text in the README describing how to use the nightly Rust compiler with this project.  Let's instead add a `rust-toolchain.toml` file so that the nightly compiler is used automatically, and let's redraft the README in that light.
With this revision, we'll add a section on installing dependencies in which we'll describe how to ensure that the nightly compiler is installed and up to date and how to install `mdbook`.
When describing how to clone the project, we'll suggest that people clone the URL ending in `.git`.  This is what GitHub recommends, and it removes a level of redirection which sometimes matters.
For people who want to download a ZIP file rather than using `git`, we'll provide a direct link rather than simply referencing the GitHub page.
When describing how to …
=> Add `rust-toolchain.toml` and revise README

src/conditional-compilation.md
This adds documentation for `#[cfg(target_abi = "...")]`.
Marking as draft until `target_abi` is stable but feedback is welcome.
See tracking: https://github.com/rust-lang/rust/issues/80970#issuecomment-1877682716
=> Document `target_abi`

src/patterns.md
The Patterns chapter didn't say that struct patterns can match enum values, and didn't document how refutability works for enums.
=> Patterns and enums

src/tokens.md
Forms like `'ab'c` are rejected, so we need some way to explain why they don't tokenise as two consecutive LIFETIME_OR_LABEL tokens.
I think the best way to do this, given the Reference's current approach, is simply to add "not immediately followed by `'`" to the lexer rules for the lifetime-like tokens.
That matches what the implementation (`lifetime_or_char()`) is doing, so it's not likely to be wrong, and this chapter already has some cases of lookahead of this sort.
It also means there can be no ambiguity between CHAR_LITERAL and these tokens (I think the intent is that we have a traditional "longest matching token wins" rule, which would give the right result here, but that isn't explicitly stated anywhere).
=> Lexer: say that lifetime-like tokens can't be immediately followed by '

src/comments.md, src/crates-and-source-files.md, src/input-format.md, src/tokens.md
Moves the descriptions of BOM removal, CRLF normalisation, and shebang removal to the "Input format" page.
So the rest of the _Lexical structure_ chapter now assumes CRLF normalisation has already taken place.
Covers some of #626 and #527.
Closes #1252
I think this supersedes #1332
=> Input format

src/expressions/literal-expr.md
Write `u32::from_str_radix` rather than `u8::from_str_radix` for unicode escapes.
=> Literal expressions: fix mistake in the definition of unicode escapes

src/crates-and-source-files.md
Tracking issue: https://github.com/rust-lang/rust/issues/28937
I'd like to push for stabilizing this, so writing a documentation PR to go along with it.
@rustbot label +S-waiting-on-stabilization
=> Document importing `main`

src/procedural-macros.md
I copy+pasted this example into my code and the `clippy::to_string_in_format_args` lint fired.
=> Fix clippy warning in procedural macro example

src/type-layout.md
The rust-reference implies that 64-bit types are aligned to 32-bit for platforms with 32-bit addresses. This is not necessarily correct. Fix the wording.
Note that there is no general rule how data-types greater than the native address size are aligned. On most Unix'y systems, they use the native alignment of the platform. However, the Windows ABI aligns them to their size (up to at least 64-bit).
There are advantages for either of those decisions. But we should at least make clear that there is no fixed rule for 32-bit platforms.
=> type-layout: be more specific about 32-bit alignments

src/attributes/type_system.md
I was surprised by this behavior and it led me to believe [Clippy was issuing a false positive](https://github.com/rust-lang/rust-clippy/issues/12675) because I thought that `#[non_exhaustive]` was largely ineffective on unit structs. But in fact it does have notable effects, and these effects were not previously documented in the reference except in the matching section.
Closes #1097
=> Document how `non_exhaustive` interacts with tuple and unit-like structs.

src/type-layout.md
These changes are intended to make the section more informative and readable, without making any new normative claims.
* Specify that the alignment might be _less_ than the size, rather than just that it might be different. This is mandatory and stated in the previous section, but I think it's useful to reiterate here.
* Mention `u128`/`i128` as another example of alignment less than size, so that this doesn't sound like a mainly 32-bit thing.
* Add `usize`/`isize` to the size table, so it can be spotted at a glance.
=> Expand and clarify primitive alignment

src/attributes/codegen.md
Companion PR to https://github.com/rust-lang/rust/pull/117457.
Waiting for that to be accepted first.
=> Stabilize Wasm target features that are in phase 4 and 5

src/attributes.md, src/attributes/debugger.md
For stabilization in https://github.com/rust-lang/rust/pull/120845.
=> Add docs for `#[collapse_debuginfo]` attribute

src/patterns.md
Done as recommended by the [the stabilization guide](https://rustc-dev-guide.rust-lang.org/stabilization_guide.html).
When [exclusive range patterns](https://github.com/rust-lang/rust/issues/37854) are stabilized, this PR will update the reference appropriately to reflect this and remove the mention of there being no exclusive range patterns.
There's no stabilization PR yet, I'm simply going through the guide for now.
=> patterns: include yet unstable exclusive range patterns

src/expressions/block-expr.md, src/expressions/path-expr.md
Fixes https://github.com/rust-lang/rust/issues/112090
I think this has been our intention for a while (ever since https://github.com/rust-lang/rust/issues/67191 landed), but was never properly decided, so it likely needs t-lang FCP.
=> document guarantee about evaluation of associated consts and const blocks

src/patterns.md
Updates the reference for https://github.com/rust-lang/rfcs/pull/3535.
Tracking issue: https://github.com/rust-lang/rust/issues/120362.
This is not 100% implemented yet:
- parts of it are pending on https://github.com/rust-lang/rust/pull/116284
- also the (recursive) structural equality checker in rustc currently sometimes issues a future-compat lint instead of a hard error; this may still take some tome to phase out (we need to first bump that to a "future-compat lint that is also shown in dependencies")
- violations of the `T: PartialEq` currently also just give a future-compat lint, not a hard error
=> update patterns.md for const pattern RFC

src/items/external-blocks.md
There's an open PR rust-lang/rust#124048 to support C23's variadics without a named parameter in Rust's extern blocks. Currently, it's waiting on approval from T-lang to get merged.
This PR removes the line "There must be at least one parameter before the variadic parameter" and adds an example to highlight that Rust supports variadics without any named parameters.
Opening this now so it can get merged if and when the implementation gets approved by T-lang.
=> Mention Variadics With No Fixed Parameter

src/items/unions.md
Macros can accept and generate unions with empty field lists, which means the rule about prohibiting empty union field lists is more about semantics rather than syntax. This can be seen by compiling [this](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a3c7c2e0cafb924ead10ded4dd93a4b1).
=> union syntax fix for empty field list

src/types/impl-trait.md
When `impl Trait` in function parameters was added, it was not allowed to specify generics at all when any of the function parameters used `impl Trait`. [That is no longer the case.](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=57497ffc80ae5b1efad80567d4a02804) This restriction was lifted in [1.63.0](https://releases.rs/docs/1.63.0/) by <https://github.com/rust-lang/rust/pull/96868/>, but this instance in the reference was missed. I've removed the outdated sentences.
The original last line:
> Therefore, changing the function signature from either one to the other can constitute a breaking change for the callers of a function.
would be correct, but even in the old version, it didn't explain how converting `impl Trait` to generics could be a breaking change, and I …
=> Remove outdated info about impl Trait in parameters and generics in the same function

src/expressions/underscore-expr.md
Add examples of `_`-expressions.
In particular, assignment to `_` is something I constantly use while prototyping.
=> underscore-expr: add more examples

src/types/tuple.md
To illustrate the existence of 1-ary tuple types with the obligatory comma, as mentioned here #1511
Fixes #1511
=> Add example of 1-ary tuple type

src/attributes.md, src/attributes/diagnostics.md
This PR is created in preparation to stabilize the `lint_reasons` feature. I hope this covers everything :upside_down_face:
Tracking issue: https://github.com/rust-lang/rust/issues/54503
=> Document new `#[expect]` attribute and `reasons` parameter (RFC 2383)

src/crates-and-source-files.md, src/items/extern-crates.md
This removes some old stubs that were needed due to the way the link checker works (it doesn't handle the `<script>` redirections).
=> Remove stubs needed for the link checker.

src/conditional-compilation.md
`target_family` can take multiple values, but this is not particularly clear in the documentation. To resolve this, I've changed the example to document this. I'm not entirely happy with the formatting, would like guidance if you think there's a better solution?
[A crater run](https://github.com/rust-lang/rust/pull/124355#issuecomment-2091278128) found a few instances where this value was incorrectly assumed to be a single value.
This is related to https://github.com/rust-lang/cargo/pull/14165, I'm not sure if that change would be enough?
=> Provide an example of `target_family` being multi-valued

src/items/functions.md
See the commit messages for details.
=> Improvements to `items/functions.md`

src/behavior-considered-undefined.md, src/items/external-blocks.md
Fixes https://github.com/rust-lang/unsafe-code-guidelines/issues/514
=> more explicitly explain the UB around immutable extern statics

src/linkage.md
This confused me for a while, but this is just fundamentally how static libraries work.
Wading through some history on this, I think when specifying `--crate-type=staticlib`, rustc used to output the `--print=native-static-libs` note by default, but it doesn't anymore, so let's document it instead!
=> Add note about static libraries not linking their dependencies

src/inline-assembly.md
=> Clarify that `asm!` blocks can be duplicated or deduplicated by the compiler

src/inline-assembly.md
The correct directive name should be `.insn`. [Here is the issue in rust repository.](https://github.com/rust-lang/rust/issues/90558)
=> '.inst' in inline-assembly changed to '.insn'

src/behavior-considered-undefined.md
As decided in https://github.com/rust-lang/unsafe-code-guidelines/issues/510
=> elaborate on slice wide pointer metadata

src/attributes/limits.md
Bit of a cop out, but I don't think we should actually do anything more here.
I think deprecating the limit attribute is a bit overkill, since users who add it to their code because nightly *just* started telling them it's necessary shouldn't be punished imo.
https://github.com/rust-lang/rust/pull/127670#issuecomment-2227383876
=> Suppress type length limit test and note that it is not enforced

src/items/type-aliases.md
The other preceding paragraphs all link to `associated type` in the same place, for consistency, I think it makes sense to add a link here as well.
=> add missing associated type link in type-aliases.md

src/expressions/loop-expr.md, src/items/generics.md, src/tokens.md, src/trait-bounds.md
This adds `'_` to the LIFETIME_OR_LABEL. It has been supported syntactically since before 1.0.
=> Add '_ to LIFETIME_OR_LABEL

style-check/src/main.rs
This removes the broken-link *markdown* checker. Unfortunately it is not compatible with the mdbook-spec plugin, which adds implicit link definitions for things like rules and std links. The link checker needs to run *after* the preprocessor, but there isn't a particularly good way to do that. Eventually this should be built-in to mdbook which is capable of doing that. We'll just need to be extra careful and diligent to avoid these.
The *html* link checker still runs, which runs after content generation.
=> Remove broken link checker.

.github/workflows/main.yml, style-check/src/main.rs
Just to help enforce a consistent style on the code.
=> Enforce `cargo fmt` on the style-check code.

src/items/static-items.md
This updates the mutable static item example to fix some issues with how it works and how it is presented.
First, the unsafe operations are wrapped in an `unsafe` block so that it doesn't trigger `unsafe_op_in_unsafe_fn`.
Second, it switches the mutation example to use addr_of_mut to avoid the undefined behavior, and to compile correctly in 2024 edition.
Third, it rewrites the second example to be safe with a different description. My understanding is that the original example was written at a time when it was considered that any potential race condition was considered unsafe. However, that is no longer a widely held view. The example has been rewritten to illustrate the two different ways you can wrap mutable static access.
This is an alternative to …
=> Update mutable static items example for modern Rust.

src/expressions/block-expr.md
This link was pointing to a redirect, but the redirect isn't capable of handling linking to a specific section. This updates the link to point to the intended part of the chapter.
=> Update link for unsafe blocks.

src/behavior-considered-undefined.md
This is the last step for https://github.com/rust-lang/rust/issues/117945. The corresponding change in rustc has already landed (https://github.com/rust-lang/rust/pull/117329).
Fixes https://github.com/rust-lang/rust/issues/117945
=> update 'dangling pointers' to new zero-sized rules

src/behavior-considered-undefined.md
I've always been bothered by the fact that was are listing what is *invalid*, which just feels all backwards. So this PR changes that list to instead enumerate what is valid. We also move that list into its own subsection to give a bit more structure to this entire page.
=> re-structure 'invalid values' enumeration to instead define what is *valid*

src/keywords.md
Had to figure this out for rust-analyzer and noticed that the reference is lacking here (arguably not an important detail as 2015 is rather old :)
Sourced from rustc here: https://github.com/rust-lang/rust/blob/339015920d0787ea14aee05fca2c205683c525f9/compiler/rustc_parse/src/parser/ty.rs#L722-L731 and https://github.com/rust-lang/rust/blob/339015920d0787ea14aee05fca2c205683c525f9/compiler/rustc_parse/src/parser/ty.rs#L84-L99
=> Describe all cases for which the weak `dyn` keyword is parsed as a keyword

src/linkage.md
Fixes https://github.com/rust-lang/rust/issues/111593
----
CC @bjorn3
=> linkage: Add a note about symbol visibility and unused sections to the paragraph about staticlibs

src/attributes.md, src/items/constant-items.md, src/items/enumerations.md, src/items/extern-crates.md, src/items/external-blocks.md, src/items/functions.md, src/items/generics.md, src/items/modules.md, src/items/static-items.md, src/items/structs.md, src/items/traits.md, src/items/type-aliases.md, src/items/unions.md, src/items/use-declarations.md, src/names/namespaces.md, src/paths.md, src/patterns.md, src/procedural-macros.md
This expands on several sections to specify exactly which names are introduced by items. This also contains a few tangential updates, such as explaining what `Self` is and how it is defined, and a major update to the `use` chapter.
This does not cover everything; that's a multi-year effort. This is intended as a small step along that journey. One giant gaping hole is covering expansion and peculiarities related to that. The ambiguities section is also incomplete.
Closes #129
cc #487
cc #568
=> Add details on how names are introduced.

mdbook-spec/src/std_links.rs
This fixes std links like `core::result::Result<T,S>` which contain commas.
=> Fix std-links for generics with commas.

theme/reference.css
This is causing weird issues where the width of blockquotes gets smaller on wider screens. I don't particularly want to try to fix it, and I'm personally fine with the default mdbook styling. I think we can revisit this later to see if it can be made better.
=> Remove custom blockquote styling

src/items/external-blocks.md, src/items/functions.md, src/items/static-items.md, src/keywords.md, src/types/never.md, src/unsafe-keyword.md, src/unsafety.md
This goes after this is merged:
- https://github.com/rust-lang/rust/pull/127921
...and CI should be happy after that.
I'd say that also this is kind of WIP until someone wouldn't mind fixing my broken english :).
r? @traviscross 
Tracking:
- https://github.com/rust-lang/rust/issues/123743
=> Changes for unsafe extern blocks (RFC 3484)

src/inline-assembly.md
in order to stabilize https://github.com/rust-lang/rust/issues/93332.
cc @Amanieu
=> add the `const` operand to docs for inline assembly

src/behavior-considered-undefined.md, src/expressions/operator-expr.md, src/types/textual.md
Usually we use "undefined behavior", but in a few cases it's "Undefined Behavior" instead. Let's make this consistent at least across the reference.
=> don't capitalize Undefined Behavior

src/abi.md, src/attributes.md, src/unsafe-keyword.md, src/unsafety.md
Reference docs for https://github.com/rust-lang/rust/issues/123757
I'm not sure how much detail I need to go into for these changes, or how the reference itself is laid out, or even if I'm missing anything.
=> Add some basic docs for unsafe attrs

src/behavior-considered-undefined.md, src/expressions.md, src/expressions/operator-expr.md, src/items/static-items.md, src/type-layout.md, src/types/pointer.md
Accompanying PR for https://github.com/rust-lang/rust/pull/127679.
Fixes https://github.com/rust-lang/rust/issues/64490.
I reworded things to avoid the "address-of" terminology, since a pointer is not just an address.
=> operator expressions: add &raw

src/type-layout.md
https://github.com/rust-lang/rust/issues/77841#issuecomment-716575747 FCP'd a modification to the specification of `repr(transparent)` to check for *at most* one non-1-ZST field in `repr(transparent)`.
This was changed in the compiler in: https://github.com/rust-lang/rust/pull/86279
The reference was never updated, leading to confusion: https://github.com/rust-lang/rust/issues/129029
=> Tweak `repr(transparent)` to mention requiring *at most* one non-1-ZST

src/behavior-considered-undefined.md
This needs to be stated explicitly due to https://github.com/rust-lang/unsafe-code-guidelines/issues/493: with code like
```rust
let x: &'static Option<Cell<i32>> = &None;
```
it is currently UB to write to this memory, even though there is an `UnsafeCell`. This is because const-promotion notices that the *value* has no `UnsafeCell` and therefore places it in read-only global memory. However, our aliasing rules for interior mutability are likely not going to do such value-based reasoning, so we need to explicitly say that const-promotion is allowed to make things read-only here -- that's what this PR does.
Given that we have not yet said what exactly our aliasing model is, this could be considered a NOP for now. But it doesn't hurt to be explicit, and it seems likely that will eventually …
=> bytes inside implicitly const-promoted expressions are immutable

src/visibility-and-privacy.md
Arbitrary path expressions aren't allowed here (in particular, the path can't rely on another `use` statement).
=> Say that `pub(in path)` can't depend on `use` statements

src/destructors.md
This adds spec identifier syntax for destructors.md
=> Add spec identifier syntax to destructors.md

src/const_eval.md
Accompanying reference update for https://github.com/rust-lang/rust/pull/128596.
The float semantics RFC decided that this is *not* a guarantee we actually provide (and I am surprised to see that this was ever documented here, since we have [other plans](https://github.com/rust-lang/rust/issues/124625) that will make this even less true):
> Calling a const function at compile-time
will always yield the same result as calling it at runtime, even when called
multiple times.
Therefore, I removed this paragraph. I am not sure what its purpose was.
Also fixes https://github.com/rust-lang/reference/issues/1581.
=> const_eval: update for const-fn float stabilization

mdbook-spec/src/lib.rs, mdbook-spec/src/std_links.rs
This synchronizes the lints in mdbook-spec that are denied in rust-lang/rust. This unblocks updating the books.
=> Sync denied lints with upstream

docs/authoring.md, src/expressions/method-call-expr.md, src/introduction.md, src/items/associated-items.md, src/macros-by-example.md, src/names/preludes.md, src/paths.md, src/patterns.md, src/tokens.md, src/types/trait-object.md, src/visibility-and-privacy.md
The existing text was inconsistent with whether or not the "d" was capitalized. This goes the route of using a lowercase "d" to match the style of using sentence-case for headings.
=> Be consistent about how "Edition differences" is capitalized

src/introduction.md
This adds a description of the rule identifiers, along with a warning that these are not going to be stable in the short term. Once things have settled a bit, I think we can remove the warning.
Closes #1573
=> Add a description of rule identifiers

mdbook-spec/src/lib.rs
This adds the `r-` prefix to HTML IDs generated for rule names. This fixes a problem where the HTML IDs may conflict with existing markdown headers. For example, `## Crate` conflicts with `r[crate]`. This is done with the expectation that no headers will start with just the letter "r".
=> Add a prefix to rule HTML IDs

src/names/scopes.md, src/trait-bounds.md, src/types/impl-trait.md
The Reference didn't include any description of capturing or capturing behavior for `impl Trait` opaque types.  Let's describe briefly what capturing is and what the currently-stable automatic capturing rules are.  Then let's describe the syntax and behavior of RFC 3617 precise capturing.
Precise capturing is currently undergoing stabilization in:
- https://github.com/rust-lang/rust/pull/127672
Tracking issue:
- https://github.com/rust-lang/rust/issues/123432
cc @compiler-errors @ehuss
=> Add capturing and precise capturing rules

src/items/functions.md
Unblocks https://github.com/rust-lang/rust/pull/129935
=> dont use stdcall on x86_64 where it is not a valid ABI

mdbook-spec/src/lib.rs, src/behavior-considered-undefined.md, src/conditional-compilation.md, src/expressions/method-call-expr.md, src/expressions/operator-expr.md, src/introduction.md, src/items/external-blocks.md, src/names/preludes.md, src/patterns.md, src/type-layout.md, theme/reference.css
This switches the warning div blocks to use the [admonition](https://github.com/rust-lang/reference/blob/master/docs/authoring.md#admonitions) feature provided by mdbook-spec.
This also includes several fixes to the admonition support, described in the individual commits.
The rendering should essentially look identical in most cases, with some minor fixes for multi-paragraph warnings, and more consistent styling of the word "Warning".
=> Switch warning blocks to use admonitions

src/inline-assembly.md
As pointed out by @Freax13 in https://github.com/rust-lang/reference/issues/1350#issuecomment-2320193484, we already allow `asm!` blocks with `options(nomem)` or `options(readonly)` to read from or write to *private memory*, which I believe refers to memory that is allocated from within the `asm!` block and not accessible from the outside (and please correct me if I'm wrong on this):
https://github.com/rust-lang/reference/blob/c118ff6f99b2b2c9dd4fa2684715e6e06ff5bc7a/src/inline-assembly.md?plain=1#L577-L582
Since we already allow this, this PR also documents it on the `nomem` and `readonly` options directly, in addition to the documentation that can be found lower on the same page. No functional changes intended.
closes https://github.com/rust-lang/reference/issues/1350
r? @Amanieu …
=> `asm!`: clarify that `nomem` / `readonly` can access private memory

src/attributes/type_system.md
Added a more complete example that explains what is allowed and what's not allowed when the non_exhaustive attribute is in use.
=> Fix improper documentation on casting non_exhaustive enums

src/const_eval.md
This is the reference PR accompanying https://github.com/rust-lang/rust/pull/129195.
Fixes https://github.com/rust-lang/rust/issues/57349
Fixes https://github.com/rust-lang/rust/issues/80384
=> const_eval: update for const_mut_refs and const_refs_to_cell stabilization

src/items/functions.md
to stabilize https://github.com/rust-lang/rust/issues/64926.
This feels a little bare-bones, but I guess that is sort of what the spec is for: just factual statements.
=> stabilize `const_extern_fn`

src/behavior-considered-undefined.md
In MIR, locals are the only place "roots" since statics get turned into `*PTR` where `PTR` is a constant pointer pointing to that static... but in the surface language, `STATIC.foo.bar` arguably has `STATIC` as its root and contains no `*`, so let's add that as a possible case here.
=> Places based on misaligned pointers: also mention 'static's as a possible base for place projections

src/comments.md
It is unintuitive that the Markdown contained within doc comments is not actually part of their syntax, as evidenced in the linked issue. This can result in certain block doc comments parsing (or rather, failing to parse) in an unintuitive way.
Closes rust-lang/rust#129685.
=> Document limitations on block doc comments

src/input-format.md
This adds spec identifier syntax to `input-format.md`
=> Add spec identifier syntax to input-format.md

src/interior-mutability.md
This adds spec identifier syntax to interior-mutability.md
=> Add spec identifier syntax to interior-mutability.md

src/items/constant-items.md
Constants are values, they have no address, so "address of a constant" is a nonsensical concept.
=> do not talk about the 'address of a constant'

docs/authoring.md
When I updated the authoring guide to add standard library links, I missed this section at the top.
=> Authoring guide: clarify standard library linking

src/macros-by-example.md, src/procedural-macros.md
This adds identifiers to macros-by-example.md and proc-macro.md.
macro-ambiguity.md is intentionally excluded due to complexity.
=> Add spec identifier syntax to macro subchapters

src/macro-ambiguity.md, src/macros-by-example.md
Draft pending stabilization of 2024.
Tracking issue: https://github.com/rust-lang/rust/issues/123742
=> Add `expr_2021` macro fragment specifier

docs/authoring.md
This adds guidelines for using spec identifier syntax in the reference.
It is also intended to aid review in the PRs for adding spec identifier syntax.
=> Explain how to name rule identifiers

src/inline-assembly.md
Currently, clobber_abi doc lists `"efiapi"` as a supported ABI of LoongArch:
https://github.com/rust-lang/reference/blob/e61a925ee051c75c0dd71035c8e4e6b3383a0f3d/src/inline-assembly.md#L487
But only `"C"` and `"system"` are actually supported: https://github.com/rust-lang/rust/blob/267cf8d3b20e98315c8e0ddf1d7020f60f664249/compiler/rustc_target/src/asm/mod.rs#L942
r? @Amanieu
=> Fix inline-assembly documentation for LoongArch

src/trait-bounds.md
After https://github.com/rust-lang/rust/pull/127054, the `T: ?Trait` and `T: for<...> Trait` syntax is mutually exclusive, and this code no longer compiles:
```rust
fn foo<T: ?for<> Sized>() {}
```
Update the reference to reflect that.
|before|after|
|:-:|:-:|
|![](https://github.com/user-attachments/assets/1f19a572-71e5-4ff7-89e6-41bf3c5dd005)|![](https://github.com/user-attachments/assets/67689802-4904-4a6b-b3dd-42acb1cf2f5c)|
r? @compiler-errors
=> trait bounds grammar: make `?` and `for<>` mutually exclusive

.github/workflows/main.yml
This adds a CI job which will generate a preview of the reference when a PR is posted/updated.
This does not yet offer a way to view it directly. I've been looking at various options for supporting that, but that might take a while to get that ready. This particular job is a requirement of that anyways, and since it provides a benefit now, I think it would be useful to add it.
This works by uploading to a GitHub Artifact. Artifacts persist for 90 days. You can download an artifact with:
`gh run download -R rust-lang/reference -n preview-1234`
where 1234 is the PR number. And then open `preview-1234/index.html` in your browser.
GitHub may or may not make this easier in the future (https://github.com/actions/upload-artifact/issues/14).
=> Add preview artifacts in CI

src/behavior-considered-undefined.md, src/destructors.md
Fixes https://github.com/rust-lang/reference/issues/1616
This requires talking about lifetime extension to `'static` scope, which doesn't seem mentioned at all so I added a sentence and example for that.
=> Clarify definition of "immutable bytes"

src/statements-and-expressions.md, src/statements.md
This adds identifier syntax to statements.md
It also adds it to statements-and-expressions.md due to its size
=> Add identifier syntax to statements.md

src/types.md, src/types/array.md, src/types/boolean.md, src/types/closure.md, src/types/enum.md, src/types/function-item.md, src/types/function-pointer.md, src/types/impl-trait.md, src/types/inferred.md, src/types/never.md, src/types/numeric.md, src/types/parameters.md, src/types/pointer.md, src/types/slice.md, src/types/struct.md, src/types/textual.md, src/types/trait-object.md, src/types/tuple.md, src/types/union.md
This adds identifier syntax to types.md
=> Add identifier syntax to types and subchapters.

src/unsafe-keyword.md, src/unsafety.md
This adds identifiers to both unsafe-keyword.md and unsafety.md
=> Add spec identifier syntax to `unsafe-keyword.md` and `unsafety.md`

src/variables.md
This adds identifier syntax to variables.md
=> Add identifiers to variables.md

src/crates-and-source-files.md
This adds identifier syntax to crates-and-source-files.md
=> Add spec identifiers to crates-and-source-files.md

src/identifiers.md
This adds spec identifier syntax to `identifiers.md`
=> Add identifier syntax to identifiers.md

src/attributes/diagnostics.md
updates the reference to match https://github.com/rust-lang/rust/pull/121560
=> Allow `deny` inside `forbid` as a no-op

src/macro-ambiguity.md
This finishes the chapters listed in #1561
=> Add identifier syntax to macro-ambiguity.md

src/const_eval.md
This adds spec identifier syntax to const_eval.md
=> Add spec identifiers to const_eval.md

src/items/external-blocks.md
https://github.com/rust-lang/rust/pull/129935 made `unsupported_calling_conventions` a hard-error, which in turn makes this test fail. This should fix toolstate.
Additionally, I took the opportunity to also remove an `ignore` on a test with the same issue. Note that this is subtly different in that it uses an `all` instead of `any` due to being a raw-dylib.
=> Fix stdcall example broken by recent rustc change

src/macros-by-example.md
Current documentation for declarative macros seems to state that macros-by-example have call-site hygiene:
> By default, all identifiers referred to in a macro are expanded as-is, and are looked up at the macro’s invocation site.
This PR documents actual mixed-site hygiene rules and adds some examples.
=> Document mixed-site hygiene

src/macros-by-example.md
This sorts the list of macro fragment specifiers. The old list seemed to be fairly random. Perhaps it was supposed to be top-down in the sense of bigger grammatical things (item) followed by smaller (expr), but I don't feel like people would be reading it in that way.
=> Sort macro fragment specifiers

src/conditional-compilation.md
This was recently added in in https://github.com/rust-lang/rust/pull/129670.
I was on the fence whether this should be documented in `cfg_attr` versus no the attributes themselves. I decided to go with the slightly easier route.
=> Add restriction for cfg_attr with crate_type and crate_name

src/macros-by-example.md
The main text of the reference is supposed to document the behavior of the current edition, with any edition differences relegated to the *Edition differences* section. This fixes the `pat` fragment specifier to document what the current behavior is, with a link to the edition section for readers to see that it has edition-specific behavior.
=> Fix `pat` fragment specifier to be the "current" edition

src/conditional-compilation.md
This often serves as the landing page for information about which `target_*` configuration options are available. Mention that `rustc` can print the exact options available for each target.
=> Mention `--print cfg` under set configuration options

src/glossary.md, src/items/traits.md, src/type-coercions.md, src/types/trait-object.md
Supersedes #1512: In line with [T-lang's latest resolution](https://github.com/rust-lang/lang-team/issues/286#issuecomment-2338905118).
Part of rust-lang/rust#130852.
r? @traviscross
=> Rename "object safe" to "dyn compatible"

src/items/enumerations.md, src/type-layout.md
This fixes the header link for "The Rust Representation". The `<a>` tag inside the header broke mdbook's automatic header linking (which allows you to click on a header).
Additionally, this updates some of the last references of the "default" representation and instead uses the term "Rust representation" to stay consistent with the rest of the text.
=> Update some "default" representation references

src/items/generics.md, src/tokens.md, src/trait-bounds.md
This updates the lifetime grammar to accommodate https://github.com/rust-lang/rust/pull/126762 which switched to validating lifetimes pre-expansion. It also fixes a minor oversight where `'static` was always grammatically allowed in a lifetime generic parameter (but is rejected semantically).
In summary, since this is subtle: Labels no longer parse `'_` as valid. Thus, `'_` is removed from the LIFETIME_OR_LABEL token. Since `'_` is allowed by lifetimes, it has been moved to _Lifetime_.
Example:
```rust
// This is now an error in 1.81.
#[cfg(any())]
fn f() {
'_: {
break '_;
}
}
```
and the oversight that was fixed (this was always allowed, but wasn't reflected in the reference grammar):
```rust
#[cfg(any())]
fn f<'static>() {}
```
cc @compiler-errors
=> Update lifetimes for pre-expansion validation

src/types/trait-object.md
The non-auto trait does not have to be in the first position in a trait object, also mentioned [here](https://github.com/rust-lang/reference/pull/255#discussion_r170752509) and [here](https://github.com/rust-lang/reference/issues/392#issuecomment-614408780),
=> trait object constraint correction

src/inline-assembly.md
This PR is a sub-part of https://github.com/rust-lang/rust/pull/131258.
r? @Amanieu
=> Add s390x to inline-assembly documentation

src/attributes/codegen.md
This is intended to be a sibling PR to rust-lang/rust#131080 to update the reference documentation for wasm supporting two more features.
=> Add three more WebAssembly features to the list of accepted ones

src/inline-assembly.md
This PR is a sub-part of https://github.com/rust-lang/rust/pull/131781.
cc @Amanieu
@rustbot label +S-waiting-on-stabilization
=> Add Arm64EC to inline-assembly documentation

src/linkage.md
Discussed in https://github.com/rust-lang/rust/issues/73632
=> Explaining how to link mixed C/Rust binaries.

src/expressions/operator-expr.md
It think some illustrating examples will really help to convey what it means e.g. for an integer cast to truncate.
=> Add examples to clarify the casting rules

src/conditional-compilation.md, src/macro-ambiguity.md
Fix 2 typos.
If you're interested I can integrate  [typos](https://github.com/crate-ci/typos) and add it to CI to prevent these kinds of typos in the future.
=> Fix 2 typos

src/lifetime-elision.md
The question of how did this behave showed up in a rust-for-linux code review, and it would have been easier to explain had this example been present.
=> Added an additional example of lifetime elision

src/attributes.md
These list entries were missing an emdash like the rest of the entries.
=> Fix some missing emdashes

src/identifiers.md, src/tokens.md
See https://github.com/rust-lang/rust/pull/126452
=> Raw lifetimes

src/destructors.md
This was changed in https://github.com/rust-lang/rust/pull/103293 (Rust 1.67).
=> Fix rule for lazy boolean temporary drop scope

src/items/external-blocks.md, src/items/functions.md, src/unsafe-keyword.md, src/unsafety.md
This adds documentation for the edition differences for unsafe extern blocks in the 2024 edition. The main documentation was added in #1536, and this just adds what is now different in 2024.
Draft pending stabilization of the 2024 edition.
=> 2024: Add updates for unsafe extern blocks

src/names/preludes.md
Adds links for the 2024 edition prelude (https://github.com/rust-lang/rust/issues/121042).
Draft pending 2024 stabilization.
=> Add rust_2024 prelude

src/keywords.md
Following RFC 3513 and subsequent work, the `gen` keyword is reserved in the Rust 2024 edition.  Let's document that.
See tracking issue:
- https://github.com/rust-lang/rust/issues/123904
=> Document `gen` keyword as reserved in Rust 2024

src/types/function-pointer.md
Related change in compiler: https://github.com/rust-lang/rust/pull/116161
cc @traviscross @ehuss
=> Update function-pointer.md for stabilization of `extended_varargs_abi_support`

src/const_eval.md, src/items/constant-items.md, src/items/static-items.md
Tracked by rust-lang/rust#119618
Stabilization report: https://github.com/rust-lang/rust/issues/128183
Fix #1690
This PR updates the documentation to mention that now `static` items can be used for borrowing, explicitly or implicitly, which permits general use of them in `const` context.
=> `const` expression can borrow static items

src/keywords.md
This fixes a few things with weak keywords:
* The Lexer block was in an odd position (possibly a merge mistake?).
* Added the `safe` keyword to the Lexer block (missed in https://github.com/rust-lang/reference/pull/1536).
* Added the `raw` keyword (missed in https://github.com/rust-lang/reference/pull/1567).
=> Fix weak keywords

.github/workflows/main.yml, book.toml, mdbook-spec/Cargo.lock, src/destructors.md
This updates the book to use 2024 as the default edition for examples.
This required updating the mdbook dependency in order to parse the 2024 edition in the book config.
=> Update default edition to 2024 for code examples

triagebot.toml
This adds merge conflict notifications added in https://github.com/rust-lang/triagebot/pull/1856.
(Unfortunately the next PR to merge after this will notify all existing PRs with merge conflicts, pointing to the wrong PR as the culprit. Hopefully that's not too confusing.)
=> Enable triagebot merge-conflict notifications

src/attributes/diagnostics.md
When adding test annotations for this, this section was a bit difficult to attach the correct rules. The sentence about what happens with repetition belongs with `on_unimplemented.repetition`, and the `warnings` key should be more explicit about what it is for.
=> Clarify rules for on_unimplemented warnings

src/identifiers.md
This change happened in Rust 1.83.
As I understand it, rustc's behaviour here is determined by the versions of the `unicode-xid` and `unicode-normalization` crates it's built with.
These were updated to 0.2.6 and 0.1.24 respectively in
https://github.com/rust-lang/rust/pull/129624
Both of those versions update their character databases to Unicode 16.0.0.
I've checked that rustc 1.83 accepts the following (which rustc 1.82 doesn't):
````rust
let 𐗉 = "Todhri Letter Ei";
dbg!(𐗉);
````
=> Claim to follow Unicode 16 for lexing identifiers.

triagebot.toml
This adds an autolabel of S-waiting-on-review for new PRs, with similar settings used in other rust-lang repos. The intent is to help make it clearer what the status of a PR is.
=> Add triagebot autolabel

src/items/modules.md, src/types/function-item.md, src/types/impl-trait.md, src/types/textual.md
https://github.com/rust-lang/reference/pull/1618/commits/07e0394197e11ee7b8e1c018e0fb238b3d979616 seemed to have a mistake where it introduced `\1` replacing a trailing characters (presumably a search/replace error).
=> Fix paragraphs with trailing `\1`

src/types/closure.md
This updates the closure documentation to incorporate the changes for [RFC 2229](https://github.com/rust-lang/rfcs/blob/master/text/2229-capture-disjoint-fields.md) disjoint closure captures in Edition 2021. 
This is a repost of https://github.com/rust-lang/reference/pull/1059 with some changes that I applied. I'm still not 100% confident in this, but I think it is getting close.
Closes https://github.com/rust-lang/reference/issues/1066
=> Update closures for edition 2021 disjoint closure capturing

mdbook-spec/src/std_links.rs, src/expressions/await-expr.md, src/expressions/call-expr.md, src/expressions/closure-expr.md, src/items/traits.md, src/types/closure.md, src/types/function-pointer.md
r? @ehuss
Stabilization PR has all the info here: https://github.com/rust-lang/rust/pull/132706
More technical details on async closures here: https://rustc-dev-guide.rust-lang.org/coroutine-closures.html
I'm not certain how detailed I need to go here. I'm also not certain if I should edit the `src/types/closure.md` chapter to discuss when async closures implement `AsyncFn*` and `Fn*`.
=> Describe async closures

src/inline-assembly.md
- https://github.com/rust-lang/rust/pull/133422
- https://github.com/rust-lang/rust/pull/133587
Closes #1683
=> Reflect rust#133422 & rust#133587 to inline assembly documentation

mdbook-spec/src/lib.rs
This fixes an issue when linking to other rules with a syntax like `way to an [async function][items.fn.async]` on Windows. The code that is generating these link references was using native system paths, and on Windows those have backslashes instead of forward slashes, which are needed for URLs.
=> Fix rule auto-linking on Windows

src/identifiers.md
The `as` clause in `extern crate` is allowed to rename a crate name to a non-ascii identifier (because that doesn't affect the filesystem).
=> Clarify that `extern crate foo as føø` is allowed

src/SUMMARY.md, src/attributes.md, src/attributes/coverage-instrumentation.md
Since rust-lang/rust#84605 passed FCP, this adds the `coverage` attribute to the reference. Coverage instrumentation isn't mentioned in the reference elsewhere, as most of that information lies in the `rustc` book, but it feels like it should at least go here.
=> `coverage` attribute

src/patterns.md
We're adopting two changes to match ergonomics in Rust 2024 that have the effect of reserving language space:
- Rule 1C: When the DBM is not `move` (whether or not behind a reference), writing `mut`, `ref`, or `ref mut` on a binding is an error.
- Rule 2C: Reference patterns can only match against references in the scrutinee when the DBM is `move`.
Here, we document those changes in the Reference and describe the differences between editions.
cc @ehuss @Nadrieril @Jules-Bertholet
Tracking:
- https://github.com/rust-lang/rust/issues/131414
=> Document Rust 2024 match ergonomics reservations
